### ISSUE TITLE
Response Model'in Kararlaştırılması

### ISSUE THREAD

**Issue by TolgaTaner** [afet-yonetim-sistemi/ays-be#10]
**User Story**
As a frontend developer, I need to know the whole response models that return from the web service.

**Acceptance Criteria**
- Backend developers should decide it each other.
- After the decision, you should communicate with frontend developers (mobile, web)

**Comment by agitrubard** [comment]
@TolgaTaner I think we can take some action on this matter, and we can have a small meeting about it.
