### ISSUE TITLE
Atama Verilerinin İşlenmesi İle İlgili Analiz ve Mock Client Entegrasyonu

### ISSUE THREAD

**Issue by agitrubard** [afet-yonetim-sistemi/ays-be#103]
İhtiyaçların nasıl alınacağı, nasıl işleneceği ve atamaların nasıl belirleneceği ile ilgili bu issue içerisinde ufak bir analiz yapılması gerekmektedir. Ek olarak bu analiz sonrası uygulama içerisinde bir mock client oluşturularak uygun verilerin dönülmesi gerekmektedir.

- AYA tarafındaki servislerden yardım alınabilir mi diye incelenmeli.
   - AYA tarafındaki servislerin daha önce incelenmişti bununla ilgili çıkarım şu şekildeydi : `BE GO projesindeki needs resolver a bakip oradaki dataya biz de alip isleyebiliriz. Data Asenkron ilerliyor gibi, arada Kafka var.`
   - https://maps.afetbilgi.com web sitesinden veriler alınarak okunabilir.

**Comment by AhmetAksunger** [comment]
Yapılan analiz sonucunda, ihtiyaçların sağlıklı bir şekilde alınabileceği açık kaynaklı bir API bulanamadı.
Bu nedenle ihtiyaçların manuel bir şekilde girilip, listelenebileceği bir API geliştirilmeye karar verildi.
