### ISSUE TITLE
Telefon Numarası Uzunluklarının Sınırlandırılması

### ISSUE THREAD

**Issue by agitrubard** [afet-yonetim-sistemi/ays-be#111]
Bu issue içerisinde telefon numarası uzunlukları hem veritabanı katmanında hem de uygulama katmanında sınırlandırılması gerekmektedir. Veritabanı katmanında uzunlukların belirlenmesi ve uygulama katmanında da request içerisinde var olan alanların uzunluklarının sınırlandırılması gerekmektedir.

**Country Code Max Value :** `5`
**Line Number Max Value :** `10`

**Comment by ilkerCelimli** [comment]
Bu issue ile alakalı olarak, PhoneNumber ve CountryCode için long değilde , String kullanmanın daha mantıklı olacağını düşünüyorum,

Matematiksel işlem yapmayacağımız için sadece numerik bir veri tipi kullanmaya gerek yok
Ayrıca Stringlerde uzunluk kontrolleri daha basit, ve Basit bir regex pattern ile araya harf karışmasını önleyebiliriz,
Veritabanı içinde varchar'ı rahatca kısıtlayabiliyoruz zaten
