### ISSUE TITLE
Admin Kayıt Akışında Default Role Belirlenmeli

### ISSUE THREAD

**Issue by agitrubard** [afet-yonetim-sistemi/ays-be#115]
Bu issue ile birlikte Admin Kayıt akışıında request'ten gelmeyen verilerden biri olan `ROLE` verisinin `AdminUserEntity` objesine maplendiği aşamada default olarak `ADMIN` olarak atanması gerekmektedir. Buna bağlı olarak `AdminUserEntity` içerisinde de bu tanımın yapılması gerekmektedir.

**Comment by Rapter1990** [comment]
**AdminUserEntity** classına şunu tanımlamız gerekir.

```
@Enumerated(EnumType.STRING)
@Column(name = "ROLE")
private AdminRole role;
```

AdminRole enum class tanımı şu şekilde olmalı

```
public enum AdminRole  {

    ADMIN,
    SUPER_ADMIN

}
```


**AdminUserRegisterRequestToAdminUserEntityMapper** classındaki `mapForSaving` şu şekilde yapabiliriz.

```
default AdminUserEntity mapForSaving(AdminUserRegisterRequest registerRequest, String encodedPassword) {
        return AdminUserEntity.builder()
                .id(AysRandomUtil.generateUUID())
                .institutionId(registerRequest.getInstitutionId())
                .username(registerRequest.getUsername())
                .email(registerRequest.getEmail())
                .password(encodedPassword)
                .firstName(registerRequest.getFirstName())
                .lastName(registerRequest.getLastName())
                .countryCode(registerRequest.getPhoneNumber().getCountryCode())
                .lineNumber(registerRequest.getPhoneNumber().getLineNumber())
                .status(AdminUserStatus.NOT_VERIFIED)
                .role(AdminRole.ADMIN)
                .build();
    }


```

Kontrol edebilirseniz sevinirim .

@agitrubard @enig @skayikci @microgenius @moaydogdu @ilkerCelimli @Harun170518513 @emreylmaz

**Comment by moaydogdu** [comment]
> 

LGTM!

**Comment by Rapter1990** [comment]
Bununla ilgili gün içerisinde pull request açacağım.
