### ISSUE TITLE
Token Olmadığı Durumlarda `createdUser` ve `updatedUser` Alanları İçin Default Değer Belirlenmesi

### ISSUE THREAD

**Issue by agitrubard** [afet-yonetim-sistemi/ays-be#116]
Token'ın var olduğu durumlarda `createdUser` ve `updatedUser` alanları token içerisindeki `username` bilgisinden okunarak setlendiği için token olmadığı durumlarda bu bilgiler setlenemediğinden hata alınıyor ve işlem tamamlanamıyor. Bununla ilgili token yok ise default değerin atanması için aksiyon alınması gerekmekte.

**Comment by Rapter1990** [comment]
**BaseEntity** class'ınındaki `prePersist `ve  `preUpdate `şu şekilde yapabiliriz.

```
@PrePersist
public void prePersist() {
    Authentication authentication = SecurityContextHolder.getContext().getAuthentication();
    if (authentication != null && authentication.getPrincipal() instanceof Jwt) {
        this.createdUser = ((Jwt) authentication.getPrincipal()).getClaim(AysTokenClaims.USERNAME.getValue());
    } else {
        this.createdUser = "AYS";
    }
    this.createdAt = LocalDateTime.now();
}

@PreUpdate
public void preUpdate() {
    Authentication authentication = SecurityContextHolder.getContext().getAuthentication();
    if (authentication != null && authentication.getPrincipal() instanceof Jwt) {
        this.updatedUser = ((Jwt) authentication.getPrincipal()).getClaim(AysTokenClaims.USERNAME.getValue());
    } else {
        this.updatedUser = "AYS";
    }
    this.updatedAt = LocalDateTime.now();
}
```

Kontrol edebeilir misiniz?

@agitrubard @skayikci @microgenius @moaydogdu @enig @Harun170518513

**Comment by Rapter1990** [comment]
Bununla ilgili gün içerisinde pull request açacağım.

**Comment by agitrubard** [comment]
@Rapter1990 Burada `Optional.ofNullable()` yardımıyla yazabilriiz kodu, bu sayede daha kısa ve okunabilir olur

**Comment by Rapter1990** [comment]
@agitrubard Gerekli düzeltmeyi yaptım. Fırsat buldup kontrol edebilir misin?

**Comment by agitrubard** [comment]
> @agitrubard Gerekli düzeltmeyi yaptım. Fırsat buldup kontrol edebilir misin?
> 
> [Link](https://github.com/afet-yonetim-sistemi/ays-be/pull/122)

@Rapter1990 Göz atma fırsatı buldum, yarın boş vaktimde review edip önerilerimi yazacağım
