### ISSUE TITLE
Create ER diagram from the database schema

### ISSUE THREAD

**Issue by skayikci** [afet-yonetim-sistemi/ays-be#12]
As a developer i want to create an ER diagram so that I can create entites easily. 

Description 
Using the excel file: https://docs.google.com/spreadsheets/d/1gt5ZGzI-ApSVzRNDFss-15Ve0rKJvt3z/edit#gid=605045585 
Please create the necessary diagrams using lucid.

**Comment by Rapter1990** [comment]
I tried to devise ER Diagram for our Project.
Here is the link : https://lucid.app/lucidchart/83887f4b-3be6-41c6-97a4-f9392c5cba69/edit?viewport_loc=-82%2C594%2C2560%2C1168%2C0_0&invitationId=inv_0487efee-3fa5-430b-b901-73465f0025c7

**Comment by skayikci** [comment]
Thank you very much for this! @Rapter1990 could you please revise the diagram according to the spread sheet?
https://docs.google.com/spreadsheets/d/1gt5ZGzI-ApSVzRNDFss-15Ve0rKJvt3z/edit#gid=605045585
we have removed the user phone table for now, therefore we need to put country code and line number directly to the user object.

**Comment by skayikci** [comment]
mermaid diagram, as an example, we might need to keep it like this for future proof solution.:
classDiagram
    class User {
        +ID: int [PK]
        +USER_NAME: string
        +EMAIL: string [UNIQUE]
        +PASSWORD: string
        +FIRST_NAME: string
        +LAST_NAME: string
        +ORGANISATION_ID: int
        +COUNTRY_CODE: string
        +LINE_NUMBER: string
        +LAST_LOGIN_DATE: datetime
        +STATUS_ID: int
        +CREATED_USER: int
        +CREATED_AT: datetime
        +UPDATED_USER: int
        +UPDATED_AT: datetime
    }

    class UserType {
        +ID: int [PK]
        +NAME: string
    }

    class Organisation {
        +ID: int [PK]
        +NAME: string
    }
    class Status {
        +ID: int [PK]
        +NAME: string
    }

    User "1" *-- "1..*" UserType : belongs to
    User "1" *-- "1..*" Organisation : belongs to
    User "1" *-- "1..*" Status : has

**Comment by Rapter1990** [comment]
@skayikci Our data team will look through it as soon as possible.
