### ISSUE TITLE
I want to login via an admin panel as an institutions admin

### ISSUE THREAD

**Issue by TolgaTaner** [afet-yonetim-sistemi/ays-be#13]
⚠️ This issue requires creating an authorization infrastructure with Spring Security while it is being implemented.

--- 

**Endpoint :**
`POST - /api/v1/admin/login`

---

**Request :**
```
{
   "username": "ays-admin",
   "password": "123456"
}
```

**Response :**
```
{
   "accessToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwiaWF0IjoxNTE2MjM5MDIyLCJleHAiOjE1MTYyMzkwMjIsInVzZXJuYW1lIjoiYWRtaW4tdXNlciIsInJvbGVzIjpbIkFETUlOIiwiU1VQRVJfQURNSU4iXX0.HRUslkLQPb3ujTCu_a4vs1TF1kidjziQsi9V369Edq0"
   "accessTokenExpireIn": 1220227200,
   "refreshToken: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwiaWF0IjoxNTE2MjM5MDIyLCJleHAiOjE1MTYyMzkwMjIsInVzZXJuYW1lIjoiYWRtaW4tdXNlciIsInJvbGVzIjpbIkFETUlOIiwiU1VQRVJfQURNSU4iXX0.HRUslkLQPb3ujTCu_a4vs1TF1kidjziQsi9V369Edq0"
}
```

---

**DATABASE :**

**AYS_ADMIN**
   - ID
   - ORGANISATION_ID
   - USER_NAME
   - PASSWORD
   - COUNTRY_CODE
   - LINE_NUMBER
   - FIRST_NAME
   - LAST_NAME
   - EMAIL
   - STATUS
   - CREATED_USER
   - CREATED_AT
   - UPDATED_USER
   - UPDATED_AT

**Comment by agitrubard** [comment]
`username` and `password` will be generated by the system.

Example:
username : "123456"
password : "234325"

**Comment by agitrubard** [comment]
The related issue has been closed as the development work has been completed.
