### ISSUE TITLE
Uygulama Loglarının Dosyaya Yazılması

### ISSUE THREAD

**Issue by agitrubard** [afet-yonetim-sistemi/ays-be#135]
BE Uygulama logları sunucu üzerinde kurulu olan Docker uygulamasında container olarak çalışmakta ve loglar herhangi bir dosyaya yazılmamakta. Bu sebeple logların taşınması ve okunabilmesi zorlaşıyor. Buradaki uygulama loglarının bir dosyaya yazılması ve bu dosyanın commitlenmiyor olması gerekmektedir.

**Comment by Rapter1990** [comment]
@afet-yonetim-sistemi/back-end 

Projede `Log4j` kullandığımız için şu şekilde yapabiliriz.

**1 ) pom.xml şunu tanımlamamız gerekir.**

```
<dependency>
    <groupId>org.apache.logging.log4j</groupId>
    <artifactId>log4j-core</artifactId>
    <version>2.20.0</version>
</dependency>
```

**2 ) src/main/resources altında log4j2.xml oluşturmamız gerekir.**

```
<?xml version="1.0" encoding="UTF-8"?>
<Configuration status="warn">
    <Appenders>
        <RollingFile name="RollingFile" fileName="app.log" filePattern="app.%d{yyyy-MM-dd}.%i.log">
            <PatternLayout>
                <pattern>%d %p %c{1.} [%t] %m%n</pattern>
            </PatternLayout>
            <Policies>
                <SizeBasedTriggeringPolicy size="10MB" />
            </Policies>
            <DefaultRolloverStrategy max="5" />
        </RollingFile>
    </Appenders>
    <Loggers>
        <Root level="info">
            <AppenderRef ref="RollingFile" />
        </Root>
    </Loggers>
</Configuration>
```

loglar "app.log" dosyasına yazılır ve dosya boyutu 10MB'ı geçtiğinde yeni bir dosyaya geçilir ("app.{tarih}.log" formatında). Aynı zamanda en fazla 5 dosya saklanır, daha eski dosyalar silinir.

Logları şu şekilde tutulacak
`2023-07-23 13:45:30 INFO MyClass [main] Something happened!`

@agitrubard @moaydogdu @enig @skayikci @emreylmaz @burcubayik

Kontrol edebilir misiniz?
