### ISSUE TITLE
Build Number Yapısının Oluşturulması

### ISSUE THREAD

**Issue by agitrubard** [afet-yonetim-sistemi/ays-be#136]
Bu issue ile birlikte build number yapısının oluşturulması gerekmektedir. Build Number formatı `YYYYMMDD.HHMM` şeklinde olmalıdır. 

Bu yapıyla beraber aşağıdaki isterler karşılanmalıdır;
- Uygulama ayaklandırılırken loglara build numarası ve uygulama versiyonu yazılmalıdır.
- `/public/actuator/info` endpointinde oluşturulan build number `buildNumber` olarak dönülmeldir.

---

Documentation : https://www.baeldung.com/spring-boot-build-properties

**Comment by Rapter1990** [comment]
@afet-yonetim-sistemi/back-end 

Şu yöntemleri kullanarak sorunu çözebiliriz.

**1) Build Number Oluşturma**
Build number'ı belirtilen formatta oluşturmak için `application.properties` dosyasına şu şekilde tanımlanmalı
`build.number.format=yyyyMMdd.HHmm`

**2) Loglara Build Numarası ve Uygulama Versiyonu Eklemek**
```
<?xml version="1.0" encoding="UTF-8"?>
<configuration>

    <property resource="application.properties" />

    <appender name="CONSOLE" class="ch.qos.logback.core.ConsoleAppender">
        <!-- Diğer appender ayarları buraya gelebilir -->
        <encoder>
            <pattern>%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level %logger{36} - buildNumber:${build.number}, version:${spring.application.version} - %msg%n</pattern>
        </encoder>
    </appender>

    <root level="info">
        <appender-ref ref="CONSOLE" />
    </root>
</configuration>
```

**3) Build Numarasını `/public/actuator/info` Endpoint'inde eklemek**
```
import org.springframework.beans.factory.annotation.Value;
import org.springframework.boot.actuate.info.Info;
import org.springframework.boot.actuate.info.InfoContributor;
import org.springframework.stereotype.Component;

import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;

@Component
public class BuildInfoContributor implements InfoContributor {

    @Value("${build.number.format}")
    private String buildNumberFormat;

    @Override
    public void contribute(Info.Builder builder) {
        
        LocalDateTime now = LocalDateTime.now();
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern(buildNumberFormat);
        String buildNumber = now.format(formatter);

        builder.withDetail("buildNumber", buildNumber);
    }
}
```


Kaynak : https://www.baeldung.com/spring-boot-info-actuator-custom

**Comment by emreylmaz** [comment]
Selamlar @agitrubard ve @AhmetAksunger , @Rapter1990   umarım iyisindir. Issue'nu jiraya taşıdık takibini jirada yapabilirsin.
