### ISSUE TITLE
I want to register a volunteer to the platform as an institutions admin

### ISSUE THREAD

**Issue by TolgaTaner** [afet-yonetim-sistemi/ays-be#14]
**Endpoint :**
`POST - /api/v1/users`

---

**Header Authorization:**
```
Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwiaWF0IjoxNTE2MjM5MDIyLCJleHAiOjE1MTYyMzkwMjIsInVzZXJuYW1lIjoiYWRtaW4tdXNlciIsInJvbGVzIjpbIkFETUlOIiwiU1VQRVJfQURNSU4iXX0.HRUslkLQPb3ujTCu_a4vs1TF1kidjziQsi9V369Edq0
```

---

**Request :**
```
{
   "firstName": "John",
   "lastName": "Cash"
}
```

**Response :**
```
{
   "id": 1,
   "username": "123456",
   "password": "123456"
}
```

---

**DATABASE :**

**AYS_USER**
   - ID
   - ORGANISATION_ID
   - USER_NAME
   - PASSWORD
   - FIRST_NAME
   - LAST_NAME
   - STATUS
   - CREATED_USER
   - CREATED_AT
   - UPDATED_USER
   - UPDATED_AT

**Comment by agitrubard** [comment]
@TolgaTaner How will the password be communicated to the user?

**Comment by agitrubard** [comment]
`username` and `password` will be generated by the system.

Example:
username : "123456"
password : "234325"
