### ISSUE TITLE
Atama Silme Servisinin Hazırlanması

### ISSUE THREAD

**Issue by agitrubard** [afet-yonetim-sistemi/ays-be#149]
Bu issue ile birlikte yöneticiler kendi kurumları için daha önceden oluşturulmuş atamaları silebilecekleri servisin yazılması gerekmektedir.

---

**Endpoint :**
---
`DELETE - /api/v1/assignment/{id}`

**Header Authorization :**
---
```
Bearer eyJ0eXAiOiJCZWFyZXIiLCJhbGciOiJSUzUxMiJ9.eyJqdGkiOiJiOTdjMzgwNy03Yzc4LTRmNzAtYmFjNS00YWJlMTc2ZDlkOTkiLCJpc3MiOiJBWVMiLCJpYXQiOjE2ODcyNDAyMjUsImV4cCI6MTY4NzI0NzQyNSwiaW5zdGl0dXRpb25JZCI6Ijc3ZWNlMjU2LWJmMGUtNGJiZS04MDFkLTE3MzA4M2Y4YmRjZiIsInVzZXJMYXN0TmFtZSI6IlNpc3RlbWkiLCJ1c2VyVHlwZSI6IkFETUlOIiwidXNlckZpcnN0TmFtZSI6IkFmZXQgWcO2bmV0aW0iLCJ1c2VySWQiOiI5MjYyZjBmYy05M2RiLTRmN2UtODFjNi1hYWFkODVjMmIyMDYiLCJ1c2VybmFtZSI6ImF5cy1hZG1pbi0xIn0.Y8xTAOwhHIqRgqSdnrN7D7OkwnJE7ZbBKfjMygaparuc73WNjKgjJwBhLZ522ULaiWo217_Fw9A0r49imdPTnFGDgPZKnJCof6kTju9m3BIO8c4KcnmauhgXykwHBzsNsUdKq99d9aL72mriNX9QiuCi-T7-tQl2Nnlak338oLEC108oeGgvblXoL6XNaRcnqPnfSmbs0quxf2jJqMYvzWUsw37BnbtiZyZTG91fR9CM-wtmsQLm9-4K74R_nZ2Cq0vU5Rl4gPRGrwOGW6dEzhFSUjVwgIRBi5rSq-u28RnTZWfQ34j6NcJWYd1_0i73aBW5zPhYmBFtTHmnSuL7hw
```

**Response :**
---
```
{
    "time": "2023-06-20T05:50:25.33188038",
    "httpStatus": "OK",
    "isSuccess": true
}
```

---

**Database :**
---
- **AYS_USER_ASSIGNMENT**
   - `ID` | _VARCHAR(36)_, _NOT NULL_
   - `INSTITUTION_ID` | _VARCHAR(36)_
   - `USER_ID` | _VARCHAR(36)_
   - `DESCRIPTION` | _VARCHAR(2048)_, _NOT NULL_
   - `FIRST_NAME` | _VARCHAR(255)_, _NOT NULL_
   - `LAST_NAME` | _VARCHAR(255)_, _NOT NULL_
   - `COUNTRY_CODE` | _INTEGER(5)_, _NOT NULL_
   - `LINE_NUMBER` | _INTEGER(10)_, _NOT NULL_
   - `POINT` | _POINT_, _NOT NULL_
   - `STATUS` | _VARCHAR(50)_, _NOT NULL_
   - `CREATED_USER` | _VARCHAR(255)_, _NOT NULL_
   - `CREATED_AT` | _TIMESTAMP_, _NOT NULL_
   - `UPDATED_USER` | _VARCHAR(255)_
   - `UPDATED_AT` | _TIMESTAMP_

**Flow :**
---
- Bu servisi sadece yöneticiler görüntüleyebilir.
- Request içerisindeki tüm alanlar zorunlu olmalıdır.
- İlgili atamanın sahip olduğu `institutionId` bilgisinin ilgili kullanıcının sahip olduğu `institutionId` ile eşleştiğinden emin olunmalıdır. Bir Kurumun diğer Kurumun ataması üzerinde aksiyon alması engellenmelidir.
- Atama statüsü sadece `AVAILABLE` ise silinebilmelidir. daha sonradan silme yapılmamalıdır.
- Bu aksiyon alındığında atama tamamen silinmeli.
- Atama Statüleri
```
- AVAILABLE
- RESERVED
- ASSIGNED
- IN_PROGRESS
- DONE
```
- Unit (Service), Integration (Controller, Repository), System (End to End) testler yazılmalıdır.
- İlgili endpoint Ortak Postman Collection içerisine eklenmelidir.

**Comment by Rapter1990** [comment]
@agitrubard @moaydogdu @enig @skayikci @emreylmaz @burcubayik @Harun170518513 

**Controller** ve **Service** yapısının içeriğini biraz detaylandırmak istedim.

**Controller**

- `@PreAuthorize("hasAnyAuthority('ADMIN')")` `deleteAssignment` için kullanılacak.
- `deleteAssignment` methodu tanımlanacak. Return türü `AysResponse<Void>`
- `assignmentService.deleteAssignment`'den  return `void `olacak
- `AysResponse.SUCCESS` return edeceğiz.

**Service**

- `deleteAssignment` methodu tanımlanacak. Return türü `void`
- `identity`'den `institutionId` alacağız.
- `AssignmentEntity assignmentEntity = assignmentRepositoryfindByIdAndInstitutionIdAndStatus(id, institutionId, AssignmentStatus.AVAILABLE) ` 'den AssignmentEntity elde edeceğiz.
- Aşağıdaki işlemleri uygulayıp -> Assignment'i delete edeceğiz.
```
assignmentRepository.delete(assignmentEntity);
```


Yapıyı kontrol edebilir misiniz? Ekleyeceğimiz yerler olabilir.
