### ISSUE TITLE
Exception Handler Yapısındaki Dönüş Tiplerinin Düzenlenmesi

### ISSUE THREAD

**Issue by agitrubard** [afet-yonetim-sistemi/ays-be#152]
Exception Handler yapısındaki dönüş tipleri endpointlerde olduğu gibi standart bir yapı oluşturularak bu yapıya taşınmalı ve buna bağlı olarak testlerin de düzeltilmesi gerekmekte. Ek olarak Exception Handler'daki metotların üzerine `@HttpResponse` anotasyonu ile ilgili hatanın kodu dönülmeli.

Örneğin, `AysErrorResponse` gibi bir sınıf oluşturularak, bu objenin dönüş tipi olarak belirlenerek yapı düzenlenebilir.

**Comment by Rapter1990** [comment]
Şu şekide yapabiliriz

`AysErrorResponse `objesi oluşturup `GlobalExceptionHandler `'da `ResponseEntity<Object>` yerine `AysErrorResponse `kullanabiliriz.

```
public class AysErrorResponse {
    private AysError aysError;

    public AysErrorResponse() {
    }

    public AysErrorResponse(AysError aysError) {
        this.aysError = aysError;
    }

    public AysError getAysError() {
        return aysError;
    }

    public void setAysError(AysError aysError) {
        this.aysError = aysError;
    }
}
```

```
@ExceptionHandler(SQLException.class)
    protected AysErrorResponse handleSQLError(final SQLException exception) {
        log.error(exception.getMessage(), exception);

        AysError aysError = AysError.builder()
                .httpStatus(HttpStatus.INTERNAL_SERVER_ERROR)
                .header(AysError.Header.DATABASE_ERROR.getName())
                .build();

        return new AysErrorResponse(aysError);
    }
```

@agitrubard @moaydogdu @enig @skayikci @emreylmaz @burcubayik @Harun170518513

Kontrol edebilir misiniz?

**Comment by emreylmaz** [comment]
Selamlar @agitrubard ve @Rapter1990  umarım iyisindir. Issue'nu jiraya taşıdık takibini jirada yapabilirsin.
