### ISSUE TITLE
Test Data Builder Integration

### ISSUE THREAD

**Issue by agitrubard** [afet-yonetim-sistemi/ays-be#16]
To automatically generate test data without manually filling it, a library integration is required. The https://github.com/j-easy/easy-random library can be used for this integration.

After adding the following dependency to pom.xml, a structure can be created to generate automatic data for all DTO classes:
```
<dependency>
     <groupId>org.jeasy</groupId>
          <artifactId>easy-random-core</artifactId>
          <version>${easy-random-core.version}</version>
     <scope>test</scope>
 </dependency>
```

**Comment by skayikci** [comment]
closed with #17
