### ISSUE TITLE
Pagination/Page Değerinin Karakter Sayısı Olarak Kısıtlanması

### ISSUE THREAD

**Issue by agitrubard** [afet-yonetim-sistemi/ays-be#171]
Bu issue ile birlikte Pagination yapılan endpointlerde kullanılan Pagination objesinin içerisindeki `page` alanı karakter sayısı olarak uzun karakterler alınca 500 dönmeye başlıyor ve bu karakter sınırının oluşturulması gerekmektedir. Bu sayede 500 yerine daha fazla girilemez gibi bir hata dönmüş olacak.

**Comment by ibrahimdenizz** [comment]
@agitrubard AysPaging class'ında page için max bir değer atansa dahi 500 dönmeye devam ediyor. Spring boot tarafından json dosyasını parse edemediği için HttpMessageNotReadableException hatası veriyor. Bu hatadan nasıl field ismi alabileceğimi bulamadım ama şimdilik aşağıdaki gibi bir handler kullanabiliriz.
 
```java
    @ExceptionHandler(HttpMessageNotReadableException.class)
    protected ResponseEntity<Object> handleBodyVariableErrors(final HttpMessageNotReadableException exception) {
        log.error(exception.getMessage(), exception);

        AysError aysError = AysError.builder()
                .message(exception.getMessage())
                .header(AysError.Header.VALIDATION_ERROR.getName())
                .build();
        return new ResponseEntity<>(aysError, HttpStatus.BAD_REQUEST);
    }
```

Hatayıda şu şekilde return ediyor:
```java
{
    "time": "2023-09-17T20:16:51.999000161",
    "httpStatus": null,
    "header": "VALIDATION ERROR",
    "message": "JSON parse error: Numeric value (9999999999999999999999999999999999) out of range of long (-9223372036854775808 - 9223372036854775807)",
    "isSuccess": false
}
```
