### ISSUE TITLE
Kullanıcı Destek Durumu Akışında Bulunan Atama Kontrolünün Güncellenmesi

### ISSUE THREAD

**Issue by ibrahimdenizz** [afet-yonetim-sistemi/ays-be#188]
Kullanıcı destek durumu güncellenirken belli status'ler için kullanıcının atamaya sahip olup olmadığının kontrolü yapılıyor. Bu kontrol aşamasında eğer kullanıcı `DONE` durumunda atamaya sahip ise repository katmanı hata veriyor. 

Assignment repository katmanında `findByUserId` query'sinin dönüş tipi `Optional<AssignmentEntity>`. Eğer kullanıcının diğer durumlarla birlikte ya da birden fazla `DONE` durumunda atamaya sahip ise dönüş tipi `List` olmadığından hata veriyor.

Kullanıcın şu anda işlemde olan atamalarının kontrolü yapılması gerektiği için `DONE` durumundaki atamalar arama sırasında hariç tutulmalı. Bu yüzden atama kontrolünde `DONE` durumuna sahip olmayan atamalar aranmalı. 

Kullanıcı `DONE` durumu dışındaki durumlara sahip toplamda bir tane atamaya sahip olabilir. Böylelikle respository katmanındaki hatada çözülecektir.

**Comment by agitrubard** [comment]
Buradaki düzeltmeyi veritabanı katmanında optimize ettiğimiz için bu issue'ya ihtiyaç kalmadı. Tekrar konuştuğumuzda buradaki düzeltmeyi yapıyor oluruz. @ibrahimdenizz teşekkürler açıklamalar için, eline sağlık 🙌🏼
