### ISSUE TITLE
Save UserLocation Akışında Atılan Hata Mesajının Güncellenmesi

### ISSUE THREAD

**Issue by AhmetAksunger** [afet-yonetim-sistemi/ays-be#189]
Hata mesajı, açıklayıcı olmaması ve user id içermemesi nedeniyle değiştirilmeli.
`"USER LOCATION CANNOT BE UPDATED BECAUSE ASSIGNMENT NOT EXIST OR NOT IN PROGRESS STATUS!"`

Yeni mesaj şöyle olabilir
`"USER LOCATION CANNOT BE UPDATED BECAUSE USER DOES NOT HAVE AN ASSIGNMENT IN PROGRESS! userId:{id}"`

**Comment by agitrubard** [comment]
@AhmetAksunger eline sağlık bu şekilde ilerleyebiliriz
