### ISSUE TITLE
İstek Sınıflarında İsim ve Soyisim Değerlerinde Özel Karakter Kullanılabilme Hatasının Giderilmesi

### ISSUE THREAD

**Issue by AhmetAksunger** [afet-yonetim-sistemi/ays-be#195]
- `/api/v1/user`
- `/api/v1/assignment`
Endpointlerinde, istenen `firstName` ve `lastName` değerlerinde özel karakter (!'^+%&/()=?) kullanılabiliyor.
Bunun için request sınıflarına validasyon eklenmeli.

**Comment by AhmetAksunger** [comment]
```java
    @Pattern(regexp = "^[a-z ,.'-]+$")
    private String firstName;

    @Pattern(regexp = "^[a-z ,.'-]+$")
    private String lastName;
```
İsim ve soyisim için regex araştırdım ve şöyle güzel bi regex buldum. Tüm özel karakterleri yasaklamak doğru olmaz çünkü şöyle isimler olabilir

- Mathias d'Arras
- Martin Luther King, Jr.
- Hector Sausage-Hausen

Üstte belirttiğim regex bu senaryoların hepsini kapsıyor, onun dışında kalan özel karakter ve sayıları da girmesini önlüyor.

**Comment by agitrubard** [comment]
`@Pattern(regexp = "^[a-zA-ZÇçĞğİıÖöŞşÜü ,.'-]+$")` yerine regex pattern'ini custom validation'a çevirip `@Name` gibi bir validation annotation tanımlayıp ilgili validasyonu burası içerisinde yapabiliriz ✅
