### ISSUE TITLE
Deployment Pipeline'ın ECS İle Çalışabilecek Şekilde Düzenlenmesi

### ISSUE THREAD

**Issue by agitrubard** [afet-yonetim-sistemi/ays-be#196]
BE uygulaması artık ECS üzerine çalıştığı için, var olan pipeline EC2 üzerinde işlemler yapabilecek şekilde kurulmuştu. Buradaki yapı düzenlenerek ECS üzerinde build ve deploy edebilmesi sağlanmalı.

**Comment by ibrahimdenizz** [comment]
Kullanabileceğimiz bazı kaynakları ekliyorum.

Workflowda kullanabileceğimiz AWS tarafından sağlanan task definition deployment action'ları:
https://github.com/aws-actions/amazon-ecs-deploy-task-definition

Yukarıdaki action'ları nasıl ıygılayabileceğimizi anlatan güzel bir döküman. (İlk kısım application oluşturmayı anlatıyor. İkinci kısım bizim için yeterli.):
https://particule.io/en/blog/cicd-ecr-ecs/
