### ISSUE TITLE
Exception Altyapısına Hata Kodu İle Birlikte Alt Yapı Oluşturulması

### ISSUE THREAD

**Issue by agitrubard** [afet-yonetim-sistemi/ays-be#205]
Bu issue ile birlikte fırlatılan her hata için bir hata kodu belirlenmeli ve bu hata kodlarının maplendiği bir doküman oluşturulmalı. Bu doküman https://github.com/afet-yonetim-sistemi/ays-be/wiki içerisine oluşturulabilir.

**Comment by emreylmaz** [comment]
Selamlar @agitrubard ve @emreylmaz  umarım iyisindir. Issue'nu jiraya taşıdık takibini jirada yapabilirsin.
