### ISSUE TITLE
Aynı Atamanın Birden Fazla Kez Eklenebiliyor Olmasının Önüne Geçilmesi

### ISSUE THREAD

**Issue by agitrubard** [afet-yonetim-sistemi/ays-be#206]
Şu an için aynı atama tamamen aynı bilgilerle tekrardan eklenebiliyor. Buradaki deneyimin iyileştirilmesi için hem analiz yapılmalı hem de bu sürecin nasıl uniqueleştirilebileceği işlenmeli. 

Örnek bir fikir;
> Yakın Atamalar Institution'a Dönülerek Kullanıcının Yakınındaki Atamaları Görüntüleyebilir Buradan Da Seçimini Değiştirebilir Bu işlem Oluşturma Akışını Tamamlarken Yapılabilir

**Comment by emreylmaz** [comment]
Selamlar @agitrubard  ve @emreylmaz umarım iyisindir. Issue'nu jiraya taşıdık takibini jirada yapabilirsin.
