### ISSUE TITLE
Atamalar Kısmında Yeni Atama Eklerken Tamamen 0 Numarasından Oluşan Telefon Numarasının Sistemce Kabul Edilmesi 

### ISSUE THREAD

**Issue by ucsengun** [afet-yonetim-sistemi/ays-be#212]
Atamalar kısmında yeni atama oluştururken tamamen 0 numarasından oluşan telefon numarası sistemce kabul edilmektedir.

![image](https://github.com/afet-yonetim-sistemi/ays-be/assets/123711891/357e4b9c-ebdb-44c8-a3f9-24f8752c77b7)

**Comment by Rapter1990** [comment]
Şu yönteme göre yapabliriz. @agitrubard @ucsengun @skayikci @enig 

```
@Override
public boolean isValid(AysPhoneNumber phoneNumber, ConstraintValidatorContext context) {
    final String countryCode = phoneNumber.getCountryCode();
    final String lineNumber = phoneNumber.getLineNumber();

    if (countryCode == null || lineNumber == null) {
        return true;
    }

    final int countryCodeLength = countryCode.length();
    final int lineNumberLength = lineNumber.length();
    final boolean isCountryCodeLengthValid = countryCodeLength >= 1 && countryCodeLength <= 7;
    final boolean isLineNumberLengthValid = lineNumberLength >= 7 && lineNumberLength <= 13; // Minimum 7 digit

    final boolean countryCodeIsNumeric = countryCode.chars().allMatch(Character::isDigit);
    final boolean lineNumberIsNumeric = lineNumber.chars().allMatch(Character::isDigit);

    // New check: lineNumber should not consist entirely of zeros.
    final boolean lineNumberIsNotAllZeros = !lineNumber.matches("^[0]+$");

    final boolean isPhoneNumberLengthValid = isCountryCodeLengthValid && isLineNumberLengthValid;
    final boolean isPhoneNumberNumeric = countryCodeIsNumeric && lineNumberIsNumeric;
    
    // Checking the condition that lineNumber should not consist entirely of zeros.
    return isPhoneNumberLengthValid && isPhoneNumberNumeric && lineNumberIsNotAllZeros;
}

```

Kontrol ederseniz sevinirim.

**Comment by agitrubard** [comment]
> Şu yönteme göre yapabliriz. @agitrubard @ucsengun @skayikci @enig
> 
> ```
> @Override
> public boolean isValid(AysPhoneNumber phoneNumber, ConstraintValidatorContext context) {
>     final String countryCode = phoneNumber.getCountryCode();
>     final String lineNumber = phoneNumber.getLineNumber();
> 
>     if (countryCode == null || lineNumber == null) {
>         return true;
>     }
> 
>     final int countryCodeLength = countryCode.length();
>     final int lineNumberLength = lineNumber.length();
>     final boolean isCountryCodeLengthValid = countryCodeLength >= 1 && countryCodeLength <= 7;
>     final boolean isLineNumberLengthValid = lineNumberLength >= 7 && lineNumberLength <= 13; // Minimum 7 digit
> 
>     final boolean countryCodeIsNumeric = countryCode.chars().allMatch(Character::isDigit);
>     final boolean lineNumberIsNumeric = lineNumber.chars().allMatch(Character::isDigit);
> 
>     // New check: lineNumber should not consist entirely of zeros.
>     final boolean lineNumberIsNotAllZeros = !lineNumber.matches("^[0]+$");
> 
>     final boolean isPhoneNumberLengthValid = isCountryCodeLengthValid && isLineNumberLengthValid;
>     final boolean isPhoneNumberNumeric = countryCodeIsNumeric && lineNumberIsNumeric;
>     
>     // Checking the condition that lineNumber should not consist entirely of zeros.
>     return isPhoneNumberLengthValid && isPhoneNumberNumeric && lineNumberIsNotAllZeros;
> }
> ```
> 
> Kontrol ederseniz sevinirim.

Eline sağlık, bu şekilde yapabiliriz.

**Comment by AhmetAksunger** [comment]
#208 numaralı issue'da belirttiğim kütüphaneyi kullanırsak bu sorunun da üstesinden gelmiş oluruz.
Orada Google'ın ülkelere göre belirlediği standartlarda zaten operatörler de kontrol ediliyor.
Örneğin TR için 5XX, 850 vs gibi gerçek operatörlerle başlamıyorsa invalid olarak değerlendiriyor.

@agitrubard @Rapter1990
