### ISSUE TITLE
Pagination Kullanılan Endpointlerdeki Page Değerinin Sınırlarının Belirlenmesi

### ISSUE THREAD

**Issue by agitrubard** [afet-yonetim-sistemi/ays-be#221]
Pagination kullanılan endpointlerde kullanılan `page` değerinin sınırı olmadığı için QA ekibinden gelen bilgilere göre hem `DATABASE ERROR` hem de `PROCESS ERROR` hatalarını alıyormuşuz. Burada ilgili alan için global bir sınır belirlemeli ve bu sınır üzerinden ilgili değeri kısıtlamalıyız. Fazla bir değer geldiğinde validasyon hatası dönmeliyiz.

**Comment by Rapter1990** [comment]
Aklima direk su mantik geldi.

1. yol

    @NotNull
    @Min(0)
    private final Integer pageNumber;
    
    @NotNull
    @Min(1)
    @Max(100)
    private final Integer pageSize;


2. yol

```
public class PageNumberValidator implements ConstraintValidator<ValidPageNumber, Integer> {
    
    @Override
    public void initialize(ValidPageNumber constraintAnnotation) {
        // No initialization needed
    }
    
    @Override
    public boolean isValid(Integer pageNumber, ConstraintValidatorContext context) {
        if (pageNumber == null) {
            return true; // Null values are allowed
        }
        if (pageNumber < 0) {
            return false; // Page number must be non-negative
        }
        return true;
    }
}
```

KOntrol ederseniz sevirim.

@agitrubard @enig @skayikci @AhmetAksunger @ibrahimdenizz @burcubayik @emreylmaz @Harun170518513

**Comment by skayikci** [comment]
Bence birinci yol uygundur. Ikinci yolda fazladan impl yapmak gerekecek.

**Comment by agitrubard** [comment]
@Rapter1990 Bence de birinci yol daha uygun. Ek olarak Integer'ın alabileceği max value kadar maksimum bir sınır belirlemek daha iyi olur.

**Comment by burcubayik** [comment]
Ben de birinci yolun daha uygun olduğunu düşünüyorum. @Rapter1990 Eline sağlık :)

**Comment by Rapter1990** [comment]
Bu yapıyı şu şekilde revise edip kullanabiliriz. 


```
@NotNull
@Min(0)
private final Integer pageNumber;

@NotNull
@Min(1)
@Max(Integer.MAX_VALUE)
private final Integer pageSize;
```
@agitrubard @enig @skayikci @AhmetAksunger @ibrahimdenizz @burcubayik @emreylmaz @Harun170518513

**Comment by Nbhtozcn** [comment]
Bu issue kapanmis olarak goruyorum ama ben test caselerimde ayni hatayı almaya devam ediyorum. Bu issue'yu inceleyip bana dönüş yapar misiniz? [https://github.com/afet-yonetim-sistemi/ays-be-api-automation/issues/77](url)

**Comment by agitrubard** [comment]
> Bu issue kapanmis olarak goruyorum ama ben test caselerimde ayni hatayı almaya devam ediyorum. Bu issue'yu inceleyip bana dönüş yapar misiniz? [afet-yonetim-sistemi/ays-be-api-automation#77](https://github.com/afet-yonetim-sistemi/ays-be-api-automation/issues/77)

Selamlar, geri dönüşün için teşekkür ederim. Evet sorun çözülmemiş görünüyor, ben ilgileniyorum.

**Comment by emreylmaz** [comment]
Selamlar @Rapter1990 ve @agitrubard umarım iyisindir. Issue'nu jiraya taşıdık takibini jirada yapabilirsin. Bu issue in reviewde olduğu için kapatmıyorum.

**Comment by agitrubard** [comment]
> Selamlar @Rapter1990 ve @agitrubard umarım iyisindir. Issue'nu jiraya taşıdık takibini jirada yapabilirsin. Bu issue in reviewde olduğu için kapatmıyorum.

Selamlar @emreylmaz , bence issue'yu kapatıp Jira'daki issue'yu `In Review`'e taşıyabiliriz 👍🏼
