### ISSUE TITLE
Rezerve Edilmiş Atamaların Tekrardan Müsait Pozisyona Getirilmesi

### ISSUE THREAD

**Issue by agitrubard** [afet-yonetim-sistemi/ays-be#224]
İlgili atama 20 saniyeden fazla bir süre `RESERVED` statüsünde bekliyorsa tekrar `AVAILABLE` statüsüne alınmalıdır.

**Comment by AhmetAksunger** [comment]
Bunun için aklıma bir çözüm geldi ve araştırma yaptım.
Aklıma gelen çözüm şuydu, bir assignment'ın statüsünü `RESERVED` yaptığımız zaman 20 saniye sonra tetiklenecek bir metod yazalım ve bu metod databaseden tekrar o assignmentı çağırsın ve statusunu kontrol etsin. Eğer hala `RESERVED` , ise statüsü değiştirelim.
Bunun için Spring'te Scheduled servislerini kullanabiliriz.
```java
    private final ScheduledExecutorService scheduler = Executors.newScheduledThreadPool(1);
    public void trackAssignmentStatus(Long id) {
        scheduler.schedule(
                () -> {
                Assignment assignment = assignmentRepository.findById(id).orElseThrow();
                if (assignment.getStatus() == AssignmentStatus.RESERVED) {
                    assignment.setStatus(AssignmentStatus.AVAILABLE);
                    assignmentRepository.save(assignment);
                }
            },
            20, TimeUnit.SECONDS
        );
    }
```
Üstte yazdığım kod çağırıldıktan `20` saniye sonra sadece bir seferliğine çalışacak. Assignment statüsünü `RESERVED`'a çektiğimiz zaman bu metodu da `assignmentId` ile çağırırsak, `20` saniye sonra eğer hala statüs `RESERVED` ise bunu tekrar `AVAILABLE`'a çekmiş olacağız.

**Comment by AhmetAksunger** [comment]
Üstte belirttiğim yorumda unuttuğum bir nokta olmuş. Statüsü `RESERVED'e `çektiğimiz zaman ayrıca bu metodu çağırırsak, bir sonraki adıma geçmesi için bu kodun execute edilmesini bekleyecektir. Yani `20 `saniye boyunca kullanıcıya cevap gitmeyecektir.
O yüzden bu metodu farklı bir `Thread`'de execute etmemiz lazım.

Araştırdığımda bunu Springle basit bir şekilde yapabildiğimizi gördüm.
Metodu `@Async` anotasyonu ile işaretlemek bir seçenek. Böylece statüsü `20 `saniye sonra takip ettiğimiz metod, farklı bir threadde çalışacak ve ana akışı bozmayacak.
Bir başka çözüm ise `CompletableFuture `sınıfını kullanmak.
O da bu şekilde:
```java
    CompletableFuture.runAsync(() -> {
        assignmentStatusTracker.trackAssignmentStatus(assignment);
    });
```

**Comment by Rapter1990** [comment]
Benim aklıma şöyle bir çözüm geldi.

```
@Service
public class AssignmentStatusCheckerService {
    @Autowired
    private AssignmentRepository assignmentRepository;

    @Scheduled(fixedRate = 20000) // Run every 20 seconds
    public void checkAssignmentStatus() {
        assignmentRepository.findById(id).ifPresent(assignment -> {
            if (assignment.getStatus() == AssignmentStatus.RESERVED) {
                long timeElapsed = System.currentTimeMillis() - assignment.getReservationTime().getTime();
                if (timeElapsed > 20000) {
                    assignment.setStatus(AssignmentStatus.AVAILABLE);
                    assignmentRepository.save(assignment);
                }
            }
        });
    }
}

```

Kontrol edebilir misiniz @agitrubard , @AhmetAksunger  , @ibrahimdenizz , @skayikci , @enig , @Harun170518513 @anilhazar

**Comment by AhmetAksunger** [comment]
> Benim aklıma şöyle bir çözüm geldi.
> 
> ```
> @Service
> public class AssignmentStatusCheckerService {
>     @Autowired
>     private AssignmentRepository assignmentRepository;
> 
>     @Scheduled(fixedRate = 20000) // Run every 20 seconds
>     public void checkAssignmentStatus() {
>         assignmentRepository.findById(id).ifPresent(assignment -> {
>             if (assignment.getStatus() == AssignmentStatus.RESERVED) {
>                 long timeElapsed = System.currentTimeMillis() - assignment.getReservationTime().getTime();
>                 if (timeElapsed > 20000) {
>                     assignment.setStatus(AssignmentStatus.AVAILABLE);
>                     assignmentRepository.save(assignment);
>                 }
>             }
>         });
>     }
> }
> ```
> 
> Kontrol edebilir misiniz @agitrubard , @AhmetAksunger , @ibrahimdenizz , @skayikci , @enig , @Harun170518513 @anilhazar

Bu her 20 saniyede bir çalışacaktır. 20 saniyede bir çalışırsa cost'u çok artar. O yüzden dışardan tetiklenince çağırılan bir çözüm sundum ben.

**Comment by agitrubard** [comment]
> > Benim aklıma şöyle bir çözüm geldi.
> > ```
> > @Service
> > public class AssignmentStatusCheckerService {
> >     @Autowired
> >     private AssignmentRepository assignmentRepository;
> > 
> >     @Scheduled(fixedRate = 20000) // Run every 20 seconds
> >     public void checkAssignmentStatus() {
> >         assignmentRepository.findById(id).ifPresent(assignment -> {
> >             if (assignment.getStatus() == AssignmentStatus.RESERVED) {
> >                 long timeElapsed = System.currentTimeMillis() - assignment.getReservationTime().getTime();
> >                 if (timeElapsed > 20000) {
> >                     assignment.setStatus(AssignmentStatus.AVAILABLE);
> >                     assignmentRepository.save(assignment);
> >                 }
> >             }
> >         });
> >     }
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Kontrol edebilir misiniz @agitrubard , @AhmetAksunger , @ibrahimdenizz , @skayikci , @enig , @Harun170518513 @anilhazar
> 
> Bu her 20 saniyede bir çalışacaktır. 20 saniyede bir çalışırsa cost'u çok artar. O yüzden dışardan tetiklenince çağırılan bir çözüm sundum ben.

@AhmetAksunger aslında tam tersi dışarıdan tetiklemiyor olmamız lazım ki human cost artmasın. Arka tarafta 10 saniye, 20 saniyede bir veritabanına istek atması çok büyük bir cost yaratmaz.

**Comment by AhmetAksunger** [comment]
> > > Benim aklıma şöyle bir çözüm geldi.
> > > ```
> > > @Service
> > > public class AssignmentStatusCheckerService {
> > >     @Autowired
> > >     private AssignmentRepository assignmentRepository;
> > > 
> > >     @Scheduled(fixedRate = 20000) // Run every 20 seconds
> > >     public void checkAssignmentStatus() {
> > >         assignmentRepository.findById(id).ifPresent(assignment -> {
> > >             if (assignment.getStatus() == AssignmentStatus.RESERVED) {
> > >                 long timeElapsed = System.currentTimeMillis() - assignment.getReservationTime().getTime();
> > >                 if (timeElapsed > 20000) {
> > >                     assignment.setStatus(AssignmentStatus.AVAILABLE);
> > >                     assignmentRepository.save(assignment);
> > >                 }
> > >             }
> > >         });
> > >     }
> > > }
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > Kontrol edebilir misiniz @agitrubard , @AhmetAksunger , @ibrahimdenizz , @skayikci , @enig , @Harun170518513 @anilhazar
> > 
> > 
> > Bu her 20 saniyede bir çalışacaktır. 20 saniyede bir çalışırsa cost'u çok artar. O yüzden dışardan tetiklenince çağırılan bir çözüm sundum ben.
> 
> @AhmetAksunger aslında tam tersi dışarıdan tetiklemiyor olmamız lazım ki human cost artmasın. Arka tarafta 10 saniye, 20 saniyede bir veritabanına istek atması çok büyük bir cost yaratmaz.

Kullanıcı bir assignment search ettiği zaman tetiklenecek. Çünkü assignment search edildiği zaman bir assignment statüsü `RESERVED`'a güncellenebilir.

Bir günde 1000 kullanıcı gibi bir yüksek sayıda kullanıcının assignment aradığını düşünelim. Her bir durum için 1 kere bu kontrol sağlanacak ve gerekmediği durumlarda aktif olan hiçbir metod olmayacak. Ve toplamda da her assignment için bir kontrol yapıldığından dolayı toplam 1000 kez metod çağırılmış olacak.

Fakat 20 saniyede bir istek atılan senaryoya geçtiğimiz durumda, her gün gerek olsun veya olmasın 4320 kere bu metod çalıştırılacak.

Ayrıyetten, 20 saniyede bir metodun çağırıldığı senaryoda, şöyle bir problem var:
- Metod tam tetikleneceği zaman bir assignment'ın statüsü 18-19 saniyedir `RESERVED` statüsünde olsun.
- Dolayısıyla o tur tetiklenen scheduled servsite bu assignmentın statüsü değiştirilmeyecek. Çünkü assignment sadece 18-19 saniyedir `RESERVED` statüsünde.
- Dolayısıyla bir dahaki çağırılmada statüsü değiştirilecek. Bu da 19 + 20 = 49 saniyedir statüsü `RESERVED` demek.,
Yani aslında worst case'de her assignmenta maksimum 49,9 saniye tanınmış oluyor.
Bunu kısmak isterseniz de schedule sıklığını arttırmanız gerekir, bu sefer de bir günde 4320 değil daha fazla sayıda istek atar.

Fakat benim sunduğum çözümde tam olarka 20 saniye tanıyoruz, çünkü her `RESERVED` olduğu an asenkron olarak takip ediyoruz.

**Comment by agitrubard** [comment]
> Kullanıcı bir assignment search ettiği zaman tetiklenecek. Çünkü assignment search edildiği zaman bir assignment statüsü `RESERVED`'a güncellenebilir.
> 
> Bir günde 1000 kullanıcı gibi bir yüksek sayıda kullanıcının assignment aradığını düşünelim. Her bir durum için 1 kere bu kontrol sağlanacak ve gerekmediği durumlarda aktif olan hiçbir metod olmayacak. Ve toplamda da her assignment için bir kontrol yapıldığından dolayı toplam 1000 kez metod çağırılmış olacak.
> 
> Fakat 20 saniyede bir istek atılan senaryoya geçtiğimiz durumda, her gün gerek olsun veya olmasın 4320 kere bu metod çalıştırılacak.
> 
> Ayrıyetten, 20 saniyede bir metodun çağırıldığı senaryoda, şöyle bir problem var:
> 
> * Metod tam tetikleneceği zaman bir assignment'ın statüsü 18-19 saniyedir `RESERVED` statüsünde olsun.
> * Dolayısıyla o tur tetiklenen scheduled servsite bu assignmentın statüsü değiştirilmeyecek. Çünkü assignment sadece 18-19 saniyedir `RESERVED` statüsünde.
> * Dolayısıyla bir dahaki çağırılmada statüsü değiştirilecek. Bu da 19 + 20 = 49 saniyedir statüsü `RESERVED` demek.,
>   Yani aslında worst case'de her assignmenta maksimum 49,9 saniye tanınmış oluyor.
>   Bunu kısmak isterseniz de schedule sıklığını arttırmanız gerekir, bu sefer de bir günde 4320 değil daha fazla sayıda istek atar.
> 
> Fakat benim sunduğum çözümde tam olarka 20 saniye tanıyoruz, çünkü her `RESERVED` olduğu an asenkron olarak takip ediyoruz.


Açıklamalar için teşekkürler, bu konudaki somut çözümü ekleme şansın var mı?  CompletableFuture'da süre verilebiliyor mu? Buradaki somut çözümü paylaşabilir misin? Denemesini yapmamız gerekiyor bu tür konular için

**Comment by emreylmaz** [comment]
Selamlar @AhmetAksunger umarım iyisindir. Issue'nu jiraya taşıdık takibini jirada yapabilirsin.
