### ISSUE TITLE
[Analiz + Geliştirme] Maven Yerine Gradle Build Tool Kullanılabilir Mi?

### ISSUE THREAD

**Issue by agitrubard** [afet-yonetim-sistemi/ays-be#228]
Maven yerine performans ve ek özellikler sebebiyle Gradle Build Tool kullanılabilecek şekilde araştırma yapılması ve bununla ilgili gerekiyorsa aksiyon alınarak proje üzerinde düzenlemelerin yapılması gerekmektedir.

---

**Kaynak:** 
- https://docs.gradle.org/current/userguide/migrating_from_maven.html?_gl=1*1f0u11m*_ga*MTM0NjMxNjY5Ni4xNjk4NTc5NzY2*_ga_7W7NC6YNPT*MTY5ODU3OTc2Ni4xLjEuMTY5ODU4MDIxMS40OC4wLjA.#ex-consuming-a-pom-only-dependency
- https://gradle.org/maven-vs-gradle/

**Comment by emreylmaz** [comment]
Selamlar @agitrubard @ibrahimdenizz  umarım iyisindir. Issue'nu jiraya taşıdık takibini jirada yapabilirsin.
