### ISSUE TITLE
Kurum Yöneticisi Kayıt Başvurusu Yönetimi | Kayıt Başvurusu Özeti Servisinin Yazılması

### ISSUE THREAD

**Issue by agitrubard** [afet-yonetim-sistemi/ays-be#230]
Bu issue ile birlikte Kurum'a bağlı Yönetici Kayıt Başvurusunun, Kayıt Ekranında erişmek üzere Başvuru Özet bilgisine ulaşmak için kullanılacak servisin hazırlanması gerekmektedir.

---

**Endpoint :**
---
`GET - /api/v1/admin/registration-application/{id}/summary`

**Response :**
---
```json
{
    "time": "2023-10-16T05:59:09.376933446",
    "httpStatus": "OK",
    "isSuccess": true,
    "response": {
        "id": "9fef0c68-16fe-4b08-b15e-acadace98cd7",
        "institution": {
            "id": "6463d2dc-40e5-4c98-b317-3bf3dfc2d251",
            "name": "Test Institution"
        }
    }
}
```

---

**Flow :**
---
- Bu servis herkese açık bir servis olacak.
   - Sadece `GET - /api/v1/admin/registration-application/{id}/summary` endpointi herkese açık olarak güncellenmeli.
- İletilen `id` değeri için UUID validasyonu eklenmelidir.
- İletilen `id` değeri;
  -  Eğer doğru ise; yer alan `id`'e ait ön tanımlı bilgiler dönülecek verilicek. Ön tanımlı bilgiler içerisinde `verificationId`, `institution.id`, `institution.name` bilgisi dönülecek.
  - Eğer yanlış ise `id` değerinin bulunamadığına dair hata dönmeli.
  - Eğer iletilen `id` değerine sahip kaydın statüsü `WAITING` değil ise uygun hata mesajı dönülmelidir.
- Unit (Service), Integration (Controller, Repository), System (End to End) testler yazılmalıdır.
- İlgili endpoint Ortak Postman Collection içerisine açıklamalarıyla dokümante edilerek eklenmelidir.

**Comment by AhmetAksunger** [comment]
## Akış Diagramı
![Screenshot from 2023-10-29 23-20-39](https://github.com/afet-yonetim-sistemi/ays-be/assets/116587797/3a296eab-2d2f-4dbe-aeb2-60ef35c3da97)
