### ISSUE TITLE
Kurum Yöneticisi Kayıt Başvurusu Yönetimi | Kayıt Başvurusu Oluşturma Servisi

### ISSUE THREAD

**Issue by agitrubard** [afet-yonetim-sistemi/ays-be#231]
Bu issue ile birlikte Kurum'a ait ilgili Yönetici Kayıt Başvurusu için ön kayıt oluşturma servisinin yazılması gerekmektedir.

---

**Endpoint :**
---
`POST - /api/v1/admin/registration-application`

**Header Authorization :**
---
```
Bearer eyJ0eXAiOiJCZWFyZXIiLCJhbGciOiJSUzUxMiJ9.eyJqdGkiOiJkMDg3MDdmOC1mYzQ3LTRiOGItOWM5Yy0xMWYzMjQ0OGFlYTkiLCJpc3MiOiJBWVMiLCJpYXQiOjE2OTg1ODU0MTEsImV4cCI6MTY5ODU5MjYxMSwidXNlckxhc3ROYW1lIjoiU2lzdGVtaSIsInVzZXJUeXBlIjoiU1VQRVJfQURNSU4iLCJ1c2VyRmlyc3ROYW1lIjoiQWZldCBZw7ZuZXRpbSIsInVzZXJJZCI6ImVhMjlhMGJkLWFkNWQtNDA2OC04OGMzLWE4ODM1YjhkNTU1ZSIsInVzZXJuYW1lIjoiYXlzLXN1cGVyLWFkbWluIn0.SWxsJseLDNZjYaL9N8n4cwDiRyqgin7hGvI9fTL6ZNgr1Zt4ocY5CtNAAE3cYFBQyGtURsGHcWpLCBrg_1aPUbwWBXSHUMIfRLVyv6HmSFGyx7m3HUn7CpDhwWbB3FKRrRzuoicQ94R0t9uOjGaL3wO7xT4xG13qLu58p51tnPIJ9BWpb_8K7MBZTOw9PWp_dL7T809QKk29eeoSefUk_ToA7S6Ae7aSSh-5uMBNXV3stVyLUxF0pi54lYSrJWGGcQM4gYjGxSjPm3Xw3u0TqNoUVDUQXvGxr0InbmJMExOZ9QrQZkma3ZdNI4gFndHako0Zv6c7QclWycHnmulQXQ
```

**Request :**
---
```json
{
    "institutionId": "6463d2dc-40e5-4c98-b317-3bf3dfc2d251",
    "reason": "A Kurumundaki Bilmem Kim için oluşturuldu"
}
```

**Response :**
---
```json
{
    "time": "2023-10-16T05:59:09.376933446",
    "httpStatus": "OK",
    "isSuccess": true,
    "response": {
        "id": "9fef0c68-16fe-4b08-b15e-acadace98cd7"
    }
}
```

---

**Flow :**
---
- Bu servis sadece `SUPER_ADMIN` rolüne sahip AYS yetkilileri tarafından kullanılabilir.
- `reason` ve `institutionId` alanları zorunlu olmalı.
   - `institutionId` alanı sadece UUID formatında olmalı.
   - `reason` alanı minimum `40` karakter ve maksimum `512` karakter arasında olmalı.
- Doğrulama adımında gönderilen `insitutionId` bilgisinin var olup olmadığının kontrolü olacak.
   - Eğer ilgili kurum bulunamazsa veya statüsü `ACTIVE` değilse kurumun bulunamadığıyla ilgili hata dönülmeli.
- `AYS_ADMIN_USER_REGISTER_VERIFICATION` tablosuna `WAITING` durumunda, `ADMIN_USER_ID`'si `null` ve `INSTITUTION_ID` bilgisi ile birlikte bir kayıt eklenecek.
- Unit (Service), Integration (Controller, Repository), System (End to End) testler yazılmalıdır.
- İlgili endpoint Ortak Postman Collection içerisine açıklamalarıyla dokümante edilerek eklenmelidir.

**Comment by AhmetAksunger** [comment]
## Akış Diagramı
![Screenshot from 2023-10-29 23-20-39](https://github.com/afet-yonetim-sistemi/ays-be/assets/116587797/3a296eab-2d2f-4dbe-aeb2-60ef35c3da97)
