### ISSUE TITLE
Kurum Yöneticisi Başvuru Yönetimi | Institution Summary Servisi

### ISSUE THREAD

**Issue by agitrubard** [afet-yonetim-sistemi/ays-be#235]
Bu issue ile birlikte ekranlardaki Drop-Down List'lerde kullanılmak üzere Bütün Kurumlar ile ilgili `id` ve `name` bilgilerinin görüntülenmesi için servis yazılması gerekmektedir.

---

**Endpoint :**
---
`GET - /api/v1/institutions/summary`

**Header Authorization :**
---
```
Bearer eyJ0eXAiOiJCZWFyZXIiLCJhbGciOiJSUzUxMiJ9.eyJqdGkiOiJkMDg3MDdmOC1mYzQ3LTRiOGItOWM5Yy0xMWYzMjQ0OGFlYTkiLCJpc3MiOiJBWVMiLCJpYXQiOjE2OTg1ODU0MTEsImV4cCI6MTY5ODU5MjYxMSwidXNlckxhc3ROYW1lIjoiU2lzdGVtaSIsInVzZXJUeXBlIjoiU1VQRVJfQURNSU4iLCJ1c2VyRmlyc3ROYW1lIjoiQWZldCBZw7ZuZXRpbSIsInVzZXJJZCI6ImVhMjlhMGJkLWFkNWQtNDA2OC04OGMzLWE4ODM1YjhkNTU1ZSIsInVzZXJuYW1lIjoiYXlzLXN1cGVyLWFkbWluIn0.SWxsJseLDNZjYaL9N8n4cwDiRyqgin7hGvI9fTL6ZNgr1Zt4ocY5CtNAAE3cYFBQyGtURsGHcWpLCBrg_1aPUbwWBXSHUMIfRLVyv6HmSFGyx7m3HUn7CpDhwWbB3FKRrRzuoicQ94R0t9uOjGaL3wO7xT4xG13qLu58p51tnPIJ9BWpb_8K7MBZTOw9PWp_dL7T809QKk29eeoSefUk_ToA7S6Ae7aSSh-5uMBNXV3stVyLUxF0pi54lYSrJWGGcQM4gYjGxSjPm3Xw3u0TqNoUVDUQXvGxr0InbmJMExOZ9QrQZkma3ZdNI4gFndHako0Zv6c7QclWycHnmulQXQ
```

**Response :**
---
```json
{
    "time": "2023-10-16T05:59:09.376933446",
    "httpStatus": "OK",
    "isSuccess": true,
    "response": [
        {
            "id": "9fef0c68-16fe-4b08-b15e-acadace98cd7",
            "name": "Test Institution 1"
        },
        {
            "id": "9fef0c68-16fe-4b08-b15e-acadace98cd7",
            "name": "Test Institution 2"
        }
    ]
}
```

---

**Flow :**
---
- Bu servis sadece `SUPER_ADMIN` rolüne sahip AYS yetkilileri tarafından kullanılabilir.
- Sadece `ACTIVE` statüsüne sahip kurumların listelenmesi gerekmektedir.
- Kurumlar varsayılan olarak `name` alanına göre `ASC` yani A'dan Z'ye sıralanmalıdır.
- Unit (Service), Integration (Controller, Repository), System (End to End) testler yazılmalıdır.
- İlgili endpoint Ortak Postman Collection içerisine açıklamalarıyla dokümante edilerek eklenmelidir.

**Comment by AhmetAksunger** [comment]
## Akış Diagramı
![Screenshot from 2023-10-29 23-20-39](https://github.com/afet-yonetim-sistemi/ays-be/assets/116587797/3a296eab-2d2f-4dbe-aeb2-60ef35c3da97)

**Comment by agitrubard** [comment]
Selamlar @emreylmaz @Rapter1990,
Issue'ya ait `Labels` ve `Projects` kısmındaki `ready for development` statüsünü geliştirme review sürecine geldiği için `in review` olarak güncelleyebilir misiniz?
