### ISSUE TITLE
Kurum Yöneticisi Kayıt Başvurusu Yönetimi | Kayıt Başvurusu Tamamlama Servisi

### ISSUE THREAD

**Issue by agitrubard** [afet-yonetim-sistemi/ays-be#236]
Bu issue ile birlikte Kurum'a bağlı Yöneticinin Kayıt Başvurusunu Tamamlaması için kullanılan ve var olan `POST - /api/v1/authentication/admin/register` servisinin güncellenmesi ile ilgili geliştirmelerin yapılması gerekmektedir. 

---

**Endpoint :**
---
`POST - /api/v1/admin/registration-application/{id}/complete`

**Request :**
---
```json
{
    "username": "ays-admin-test",
    "email": "admin-test@ays.com",
    "password": "A123y456S.",
    "firstName": "Afet Yönetim",
    "lastName": "Sistemi",
    "phoneNumber": {
        "countryCode": "90",
        "lineNumber": "1234567891"
    }
}
```

**Response :**
---
```json
{
    "time": "2023-10-16T05:59:09.376933446",
    "httpStatus": "OK",
    "isSuccess": true
}
```

---

**Flow :**
---
- Bu servis herkese açık bir servis olacak.
   - Sadece `POST - /api/v1/admin/registration-application/{id}/complete` endpointi herkese açık olarak güncellenmeli.
- İletilen `id` değeri için UUID validasyonu yok ise eklenmelidir.
- İletilen mail bilgisi için mail format validasyonu yok ise eklenmelidir.
- İletilen `id` değeri;
   -  Eğer yanlış ise `id` değerinin doğru olmadığına dair hata dönmeli.
   - Eğer iletilen `id` değerine ait kaydın statüsü `WAITING` değil ise uygun hata mesajı dönülmelidir.
- İletilen `phoneNumber` değeri;
   - Eğer yanlış formatta ise ilgili validasyon hatası dönülmeli. (Bu validasyon var olabilir, sadece kontrol edilmeli.)
   - Eğer veri tabanında aynı kayıttan var ise uygun hata mesajı dönülmelidir.  (Bu kontrol var olabilir, sadece kontrol edilmeli.)
- İletilen `email` değeri;
   - Eğer yanlış formatta ise ilgili validasyon hatası dönülmeli. (Bu validasyon var olabilir, sadece kontrol edilmeli.)
   - Eğer veri tabanında aynı kayıttan var ise uygun hata mesajı dönülmelidir.  (Bu kontrol var olabilir, sadece kontrol edilmeli.)
- Bu adımda daha önceden iletilen `insitutionId` bilgisi ön tanımlı olduğu için kaldırılması gerekmektedir.
- Var olan akış ve girilen değerler ile ilgili validasyonlar sadece gerekiyorsa revize edilmeli.
- Unit (Service), Integration (Controller, Repository), System (End to End) testler yazılmalıdır.
- İlgili endpoint Ortak Postman Collection içerisine açıklamalarıyla dokümante edilerek eklenmelidir.

**Comment by AhmetAksunger** [comment]
## Akış Diagramı
![Screenshot from 2023-10-29 23-20-39](https://github.com/afet-yonetim-sistemi/ays-be/assets/116587797/3a296eab-2d2f-4dbe-aeb2-60ef35c3da97)

**Comment by emreylmaz** [comment]
Selamlar @AhmetAksunger umarım iyisindir. Issue'nu jiraya taşıdık takibini jirada yapabilirsin.
