### ISSUE TITLE
Kurum Yöneticisi Kayıt Başvurusu Yönetimi | Kayıt Başvurusu Listeleme Servisi

### ISSUE THREAD

**Issue by agitrubard** [afet-yonetim-sistemi/ays-be#237]
Bu issue ile birlikte Kurum'a bağlı Yöneticilerin Kayıt Başvurularının listelenmesi için kullanılacak servisin hazırlanması gerekmektedir.

---

**Endpoint :**
---
`POST - /api/v1/admin/registration-applications`

**Header Authorization :**
---
```
Bearer eyJ0eXAiOiJCZWFyZXIiLCJhbGciOiJSUzUxMiJ9.eyJqdGkiOiJkMDg3MDdmOC1mYzQ3LTRiOGItOWM5Yy0xMWYzMjQ0OGFlYTkiLCJpc3MiOiJBWVMiLCJpYXQiOjE2OTg1ODU0MTEsImV4cCI6MTY5ODU5MjYxMSwidXNlckxhc3ROYW1lIjoiU2lzdGVtaSIsInVzZXJUeXBlIjoiU1VQRVJfQURNSU4iLCJ1c2VyRmlyc3ROYW1lIjoiQWZldCBZw7ZuZXRpbSIsInVzZXJJZCI6ImVhMjlhMGJkLWFkNWQtNDA2OC04OGMzLWE4ODM1YjhkNTU1ZSIsInVzZXJuYW1lIjoiYXlzLXN1cGVyLWFkbWluIn0.SWxsJseLDNZjYaL9N8n4cwDiRyqgin7hGvI9fTL6ZNgr1Zt4ocY5CtNAAE3cYFBQyGtURsGHcWpLCBrg_1aPUbwWBXSHUMIfRLVyv6HmSFGyx7m3HUn7CpDhwWbB3FKRrRzuoicQ94R0t9uOjGaL3wO7xT4xG13qLu58p51tnPIJ9BWpb_8K7MBZTOw9PWp_dL7T809QKk29eeoSefUk_ToA7S6Ae7aSSh-5uMBNXV3stVyLUxF0pi54lYSrJWGGcQM4gYjGxSjPm3Xw3u0TqNoUVDUQXvGxr0InbmJMExOZ9QrQZkma3ZdNI4gFndHako0Zv6c7QclWycHnmulQXQ
```

**Request :**
---
```json
{
    "pagination": {
        "page": 1,
        "pageSize": 10
    },
    "filter": {
        "statuses": [
           "WAITING",
           "APPROVED"
        ]
    }
}
```

**Response :**
---
```json
{
    "time": "2023-10-16T05:59:09.376933446",
    "httpStatus": "OK",
    "isSuccess": true,
    "response": [
        {
            "id": "9fef0c68-16fe-4b08-b15e-acadace98cd7",
            "reason": "A Kurucusu John Doe İçin Oluşturuldu.",
            "status": "WAITING",
            "createdUser": "AYS",
            "createdAt": "2023-09-24T08:48:48",
            "institution": {
                "id": "3cfeb994-88f4-48d0-b105-309f42f91412",
                "name": "Test Institution"
            }
            "user": {
                "id": "bf438cce-1e6b-45a8-b011-22094bb8d6c8",
                "firstName": "John",
                "lastName": "Doe"
            }
        }
    ]
}
```

---

**Flow :**
---
- Bu servis sadece `SUPER_ADMIN` rolüne sahip AYS yetkilileri tarafından kullanılabilir.
- Standart `pagination` ve `filter` yapısı olmalı.
- `filter` alanı opsiyonel olmalı, filtreleme yapılmadığında gönderilmemelidir.
   - `filter` alanı gönderilmediğinde `statuses` alanı opsiyonel olmalı ve birden fazla statü değeri alabilmelidir.
- Varsayılan olarak `createdAt` alanına göre `DESC` olarak yani son oluşturulan başvuru kaydı başta olmak üzere sıralama yapılmalıdır.
- Unit (Service), Integration (Controller, Repository), System (End to End) testler yazılmalıdır.
- İlgili endpoint Ortak Postman Collection içerisine açıklamalarıyla dokümante edilerek eklenmelidir.

**Comment by AhmetAksunger** [comment]
## Akış Diagramı
![Screenshot from 2023-10-29 23-20-39](https://github.com/afet-yonetim-sistemi/ays-be/assets/116587797/3a296eab-2d2f-4dbe-aeb2-60ef35c3da97)
