### ISSUE TITLE
Mobil | Kullanıcı Atama İptal Servisi

### ISSUE THREAD

**Issue by agitrubard** [afet-yonetim-sistemi/ays-be#239]
Mobil tarafta ilgili kullanıcının atamayı iptal edebilmesi için bir servis yazılmalıdır.

**Endpoint :**
---
`GET - /api/v1/assignment/cancel`

**Header Authorization :**
---
```
Bearer eyJ0eXAiOiJCZWFyZXIiLCJhbGciOiJSUzUxMiJ9.eyJqdGkiOiIyN2RjOWNmYS03ZjY1LTRhYTQtOWVkNy1lNmNkNjU5NGI0ZWQiLCJpc3MiOiJBWVMiLCJpYXQiOjE2OTg1OTUxODMsImV4cCI6MTY5ODYwMjM4MywiaW5zdGl0dXRpb25JZCI6Ijc3ZWNlMjU2LWJmMGUtNGJiZS04MDFkLTE3MzA4M2Y4YmRjZiIsInVzZXJMYXN0TmFtZSI6IlNpc3RlbWkgMSIsInJvbGVzIjpbIlZPTFVOVEVFUiJdLCJ1c2VyVHlwZSI6IlVTRVIiLCJ1c2VyRmlyc3ROYW1lIjoiQWZldCBZw7ZuZXRpbSIsInVzZXJJZCI6ImM0YjRlNGRiLTU2NDEtNDFmNy04MjIyLWE3NmRlYjFjMDY1YyIsInVzZXJuYW1lIjoiMjMyMTgwIn0.erpEAaYLvmBL1yjMVB0nYmKqnsAbLy1vSqdlUsLFle4VswjH5FC-0vC7gpHHd0zrSB0gQdrgQw1f_frwSrgxFPORg0oyPQOl_PCeoe5wk1vMgkfM96Etnoh6nULF3vF54eAkiwAPkGpxhtsT1CE0gyR5RKDCIwmGEZmZFWbnU_H-K6w8b7CGRsU72z8LpKUEC51elJpFYJdNRvYKMvnr-NDdiJpNFgofUgm4oMbPtLHuiVXuMjXYsi2B0LBm4nDJTyYm8FpCTopJBWjJwCjAmXL9N_oWM_6atP83-lUU7e3_K9hylEJdyDCnBpCyZXkKzV8XF9bMcfsWHPwadZsFfw
```

**Request :**
---
```json
{
    "reason": "Araç Kazası"
}
```

**Response :**
---
```json
{
    "time": "2023-10-16T05:59:09.376933446",
    "httpStatus": "OK",
    "isSuccess": true
}
```

**Flow :**
---
- Bu servisi sadece kullanıcılar görüntüleyebilir.
- Bu servis içerisindeki atama ilgili kullanıcının ID bilgisi ile işlemlerin yapılması gerekmektedir. Bu kısıt `userId` bilgisi token içerisinden alınarak gerçekleştirilmelidir.
- `reason` alanları zorunlu olmalı.
   - `reason` alanı minimum `40` karakter ve maksimum `512` karakter arasında olmalı.
- İlgili atama bulunduktan sonra `ASSIGNED` veya `IN_PROGRESS` statüsünde ise aksiyon alınabilmeli.
   - Eğer bu statülere sahip kayıt yok ise kayıt bulunamadığına dair hata dönülmeli.
- `reason` bilgisi şu an için işlenmeyecek, ilerleyen dönemde kurulacak olan assignment ile ilgili aksiyonların loglanması kısmında gerekli olacak.
- Bu aksiyon alındığında atama statüsü `AVAILABLE` ve ilgili kullanıcı statüsü ise `BUSY` olarak güncellenmelidir.
- Unit (Service), Integration (Controller, Repository), System (End to End) testler yazılmalıdır.
- İlgili endpoint Ortak Postman Collection içerisine açıklamalarıyla dokümante edilerek eklenmelidir.

**Comment by AhmetAksunger** [comment]
## Problem
Kullanılan strategy pattern'de bu metodun ortaklanması sadece tek bir repository metoduna bağımlı olmamıze sebep oluyor.
```java
    private AssignmentEntity findAssignmentEntity() {
        String userId = identity.getUserId();
        AssignmentStatus assignmentStatus = this.getAssignmentSearchStatus();
        return assignmentRepository
                .findByUserIdAndStatus(userId, assignmentStatus)
                .orElseThrow(() -> new AysAssignmentNotExistByUserIdAndStatusException(userId, assignmentStatus));
    }
```
Bu issuedaki endpointde bizim user id ve statülere'a göre assignment entity filtrelememiz gerekiyor. Tek issueya göre değil.
@agitrubard

**Comment by Rapter1990** [comment]
**Çözüm Önerisi**

statusleri `Set `olarak tutup `findByUserIdAndStatuses `methodunu çağırabiliriz.

```
private AssignmentEntity findAssignmentEntity() {
    String userId = identity.getUserId();
    AssignmentStatus assignmentStatus = this.getAssignmentSearchStatus();
    Set<AssignmentStatus> statuses = new HashSet<>();
    statuses.add(assignmentStatus);

    return assignmentRepository
            .findByUserIdAndStatuses(userId, statuses)
            .orElseThrow(() -> new AysAssignmentNotExistByUserIdAndStatusException(userId, statuses));
}
```

**Comment by AhmetAksunger** [comment]
## Çözüm Önerisi
findAssignmentEntity metodunu komple kaldırıcağız. assignmentRepository ortaklanmayacak. Her strategy sınıfı assignmentRepository'i kendi handle sınıfında istediği gibi implement edecek. 
handle methodu parametre olarak AssignmentEntity almayacak.

Örnek handle sınıfı şu şekilde olmalı:
```java
    @Override
    protected AssignmentEntity handle() {

        AssignmentEntity assignmentEntity = assignmentREpository.assignmentRepository
                .istenilenRepositoryMethodu(userId, assignmentStatus)
                .orElseThrow(() -> new AysAssignmentNotExistByUserIdAndStatusException(userId, assignmentStatus));

        // Kodun Devamı
        
        UserEntity user = assignmentEntity.getUser();
        user.onRoad();
        userRepository.save(user);

        assignmentEntity.start();
        return assignmentEntity;
    }
```

**Comment by AhmetAksunger** [comment]
Şuanki çözümler bu şekilde. Eğer sizin de bir fikriniz varsa belirtirseniz iyi olur. Bu konu hakkında discordda da toplanabiliriz isterseniz.
@afet-yonetim-sistemi/back-end

**Comment by agitrubard** [comment]
> Şuanki çözümler bu şekilde. Eğer sizin de bir fikriniz varsa belirtirseniz iyi olur. Bu konu hakkında discordda da toplanabiliriz isterseniz.
> @agitrubard , @ibrahimdenizz , @enig , @moaydogdu , @skayikci

Eline sağlık, fikirsel olarak uygun gibi duruyor. Bu konu için toplanabiliriz ✅
