### ISSUE TITLE
`AYS_INVALID_TOKEN` Tablosunun Belli Aralıklarla Temizlenmesi

### ISSUE THREAD

**Issue by agitrubard** [afet-yonetim-sistemi/ays-be#253]
Çıkış yapıldığı aşamada `AYS_INVALID_TOKEN` tablosuna kaydedilen ve kullanım ömrü tamamlanmış kayıtların veri tabanından temizlenmesi gerekmektedir.

---

**Örneğin;**
`Access Token` için kullanım ömrü 2 saat ve `Refresh Token` için kullanım ömrü 1 gün olduğu senaryoda, 1 günden daha eski kayıtların `AYS_INVALID_TOKEN` tablosundan kaldırılması gerekmektedir. 

Buradaki silinme periyodunun belirlenmesi `Refresh Token`'ın kullanım ömrüne bağlı olarak değişebilmelidir. `Refresh Token` için kullanım ömrü `AYS_PARAMETER` tablosundaki `AUTH_REFRESH_TOKEN_EXPIRE_DAY` kaydıyla yönetilir.

**Comment by thelastbadalov** [comment]
bana gore bu yerde cron job kullanmak daha mantikli cunki bi tana time period vereriz @Scheduled annotation ile.
ve verdiyimiz perioda gore bu schedule caliscak ve bizim AUTH_REFRESH_TOKEN_EXPIRE_DAY kac gundurse onun gunune gore mesela 3 gundurse 3 gunden esklierin hepsini silicez.

**Comment by agitrubard** [comment]
> bana gore bu yerde cron job kullanmak daha mantikli cunki bi tana time period vereriz @scheduled annotation ile.
> ve verdiyimiz perioda gore bu schedule caliscak ve bizim AUTH_REFRESH_TOKEN_EXPIRE_DAY kac gundurse onun gunune gore mesela 3 gundurse 3 gunden esklierin hepsini silicez.

Bu şekilde ilerleyebiliriz, uygundur ✅

**Comment by AhmetAksunger** [comment]
@thelastbadalov Selamlar, issuenun labelini `in development`'a alınca aynı zamanda `Projects` kısmındaki `AYS | Back-End Board`'da da `In Development`'a alıyoruz bilgin olsun. İyi çalışmalar.

![Screenshot from 2023-11-19 15-42-59](https://github.com/afet-yonetim-sistemi/ays-be/assets/116587797/7d98d846-8d8e-4aab-b99f-cdb69620e638)

**Comment by emreylmaz** [comment]
Selamlarlar reviewde olduğu için close yapmıyorum ancak issue takibi jira da allign  şekilde ilerletilebilirse çok güzel olur emeğinize  sağlık.

**Comment by agitrubard** [comment]
> Selamlarlar reviewde olduğu için close yapmıyorum ancak issue takibi jira da allign şekilde ilerletilebilirse çok güzel olur emeğinize sağlık.


Selamlar @emreylmaz , bence issue'yu kapatıp Jira'daki issue'yu `In Review`'e taşıyabiliriz 👍🏼
