### ISSUE TITLE
Spike adding backend service on AWS

### ISSUE THREAD

**Issue by skayikci** [afet-yonetim-sistemi/ays-be#32]
As a developer, I want to spike "adding backend service on AWS", so that I can test connectivity, secret management, and other required changes.

Acceptance Criteria
1. A backend service is successfully created on AWS using this backend project.
2. The backend service can successfully handle and respond to basic requests.
3. The backend service is integrated with the AWS Secret Manager and can retrieve and use any secrets required for operation.
4. The backend service has a secure connection to the database or other external services required for operation.
5. The backend service logs relevant information for troubleshooting and debugging purposes.
6. The backend service meets any other requirements or specifications outlined by the project or development team.
7. Documentation is created that outlines the setup process and configuration for the backend service.
8. The spike is reviewed and approved by the development team and any necessary changes are made before the implementation of the production-ready backend service.

**Comment by halilturkoglucs** [comment]
For k8s deployment, we need a templating solution. Can we decide on helm, kustomize or any other solution to use?

**Comment by skayikci** [comment]
I'd say let's go with helm. If some other decisions come up, we can discuss it later.

**Comment by agitrubard** [comment]
I believe we have completed all the requirements except for the 7th item. I think it would be possible for us to work together on both creating the documentation and identifying any missing elements. 

@skayikci @halilturkoglucs

**Comment by skayikci** [comment]
@agitrubard I'm available this week, let's close this. How about tomorrow?

**Comment by agitrubard** [comment]
> I'm available this week, let's close this. How about tomorrow?

@skayikci I sometimes experience delays in receiving notifications on GitHub, so I'll message you on Discord.
