### ISSUE TITLE
integrate checkstyle, spotless

### ISSUE THREAD

**Issue by skayikci** [afet-yonetim-sistemi/ays-be#36]
As a developer I want to integrate checkstyle, so that the project is built against general best practices, coding guidelines, and the rules can be extended to comply with these best practices in the industry.

**Comment by agitrubard** [comment]
@skayikci Are the actions we have taken in this regard sufficient? How can we proceed?

**Comment by skayikci** [comment]
@agitrubard I think not, as i didn't see a build step, for instance to integrate while running clean build, etc.

**Comment by agitrubard** [comment]
> @agitrubard I think not, as i didn't see a build step, for instance to integrate while running clean build, etc.

@skayikci Would you like to review it together at a suitable time?
