### ISSUE TITLE
As an user, I want to update my support status

### ISSUE THREAD

**Issue by agitrubard** [afet-yonetim-sistemi/ays-be#44]
Before this development is implemented, the `SUPPORT_STATUS` column should be added to the `AYS_USER` table, and constraints should be added to define the allowed values for this column in the table. In this development, it is expected that the user will be able to update their own support status. Here, without obtaining any ID information, the user should be able to perform operations only based on their own token information.

**Endpoint :**
`PUT - /api/v1/user/self/status/support`

---

**Header Authorization:**
```
Bearer eyJhbGciOiJSUzUxMiJ9.eyJqdGkiOiJkYjhlNmZiYy1hMDJmLTQwMDQtOTU4ZC02M2U5MmM4ZTllM2QiLCJpc3MiOiJBWVMiLCJpYXQiOjE2ODIwMTk1MTksImV4cCI6MTY4MjAyNjcxOSwidHlwZSI6IkJlYXJlciIsInVzZXJMYXN0TmFtZSI6IlNpc3RlbWkiLCJyb2xlcyI6WyJWT0xVTlRFRVIiXSwidXNlclR5cGUiOiJVU0VSIiwidXNlckZpcnN0TmFtZSI6IkFmZXQgWcO2bmV0aW0iLCJ1c2VybmFtZSI6IjIzMjE4MCJ9.JsbCDRMy2nqMb5tjcY5IZSf0jtEp4PdJQMMZdn8lYvrSkspHGxcTNMyr8P6r8JC3t1qInAuGbybuKG6COr9LTzPB9TO15x_58zxFAqRrq9VYDb-nQhjPs9auNjfL1W1HjUd29zqA4E9ZsviVA3bbHv29Uu-PYuUMXU6Oqh4ahnrngeip4mufSfEr46voLi_QUoAmzX34cgLn526FaBA3QBqtc8GJVL5fCCTC1WXy-nTSgyUMow8gRSQowYMtm9qqlMxml-NEOKU2xyJXzpyiaf7GDErvgKwMW6CxkEFI91rt_KcM88xc3uXcz8yy6m8ZZZzff54VZ9Cp9FujD6ubtg
```

---

**Request :**
```
{
   "supportStatus": "AVAILABLE"
}
```

---

# `UserSupportStatus`
### Manuel With User Control
- `IDLE` (default)
- `READY`
- `BUSY`
- `MALFUNCTION`
- `ACCIDENT`
- `OFFLINE`

### Auto With Assignment
- `ON_ROAD`
- `RETURNING`

---

**DATABASE :**

**AYS_USER**
   - ID
   - ORGANIZATION_ID
   - USERNAME
   - PASSWORD
   - FIRST_NAME
   - LAST_NAME
   - COUNTRY_CODE
   - LINE_NUMBER
   - ROLE
   - SUPPORT_STATUS
   - STATUS
   - CREATED_USER
   - CREATED_AT
   - UPDATED_USER
   - UPDATED_AT

---
   
**Acceptance Criteria:**

- The endpoint should return AYS SUCCESS response with 200 status code if successful.

- The response should be in JSON format.

- The endpoint should require authentication and only be accessible by users with the appropriate authorization token.

**Comment by agitrubard** [comment]
@TolgaTaner, Are the explanations here in line with the requirements? Additionally, can we determine the possible status values it can take?

**Comment by mfd2144** [comment]
@agitrubard I think status can be Ready, Busy, Active/On Road, Returning .

Ready: Volunteer ready to take on any task.
Busy: The volunteer does not accept any assignment.
Active or On Road : Volunteer already accepted a mission and is still on road.
Returning: Volunteer accomplished mission and on the returning way. The system cannot assign a task to a volunteer for  this period of time.

**Comment by Rapter1990** [comment]
@emreylmaz @burcubayik @Harun170518513 

Here is the diagram of this process : [Image](https://ibb.co/wW9rBk7)

Let me know if you have any questions for that
