### ISSUE TITLE
Open source licencing

### ISSUE THREAD

**Issue by skayikci** [afet-yonetim-sistemi/ays-be#55]
As a developer contributing to an open source project,
I want to add an open source license to the project,
So that users can clearly understand the terms of use and distribution.

Scenario 1: Adding Creative Commons License

Given that I am the project maintainer,
And I want to allow users to freely use and distribute the project,
And I want to retain the copyright of the project,
And I want to allow modifications and derivative works,
And I want to require attribution from the users.
Scenario 2: Adding MIT License

Given that I am the project maintainer,
And I want to allow users to freely use, modify, and distribute the project,
And I want to require attribution from the users,
And I want to include a liability disclaimer.
Scenario 3: Adding Apache License

Given that I am the project maintainer,
And I want to allow users to freely use, modify, and distribute the project,
And I want to require attribution from the users,
And I want to include a patent grant and a contributor license.
Acceptance Criteria:

The selected license is clearly stated and easily accessible within the project's documentation or repository.
The license accurately reflects the intentions and requirements of the project maintainers.
The license is compatible with the project dependencies and any third-party libraries or components used.
The license is legally valid and widely recognized within the open source community.
Proper attribution, disclaimers, or patent grants are included as required by the chosen license.
Note: Before choosing a license, it is recommended to consult with legal professionals or experts familiar with open source licensing to ensure compliance with relevant laws and regulations.

**Comment by agitrubard** [comment]
@TolgaTaner 
If you have anything else to add, please provide it here

**Comment by TolgaTaner** [comment]
Let's talk about this in our Discord channel with others. I added this topic to my notes to create a new session. Thank you for your detailed licenses' information! @skayikci. @agitrubard basically, my opinion is more on how non-organization people should contribute it. Other things are OK with these.

**Comment by agitrubard** [comment]
@TolgaTaner @skayikci 
There is a guidance page called **GitHub Community Standards** that provides step-by-step instructions and explanations on this topic. I have created an issue related to it, and if we comment the information from this issue into the corresponding issue there, it might be more helpful.

Related issue: **#63** 

> I have created this issue for each repository. Perhaps it would be more beneficial if we add the information from this issue as comments to the issue there.
