### ISSUE TITLE
Moving The `tokenType` Field From The Body Section To The Header Section Of The JWT

### ISSUE THREAD

**Issue by agitrubard** [afet-yonetim-sistemi/ays-be#60]
The `tokenType` field in the token's body should be moved to the Header section of the JWT because it is currently unused and should be in the appropriate location.

**Current Token Example:** 
```
eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyLCJ0b2tlblR5cGUiOiJCZWFyZXIifQ._Av33mEzefaJmnaLOP9If6pGUrZm0n_xABlVmOhrcds
```

**Desired Token Example:**
```
eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c
```
---
Both tokens should be examined using [JWT IO](https://chat.openai.com/jwt.io) and the tokens should be reviewed even after the development is completed.

**Comment by Rapter1990** [comment]
@agitrubard I think this code snippet shown below helps us solve the issue.

`accessTokenBuilder.setHeaderParam(AysTokenClaims.TYPE.getValue(), OAuth2AccessToken.TokenType.BEARER.getValue())`

Can you check it?
