### ISSUE TITLE
README'nin güncellenmesi

### ISSUE THREAD

**Issue by TolgaTaner** [afet-yonetim-sistemi/ays-be#7]
- branch, commit standartlarının belirlenip eklenmeli
- GitHub projects kısmından işlerin takip edileceği not edilmeli
- Document linkinin eklenmesi

**Comment by halilturkoglucs** [comment]
3. Icin istenilen dokumanin linkini/kendisini buraya ekleyebilir miyiz

**Comment by halilturkoglucs** [comment]
PR: https://github.com/afet-yonetim-sistemi/ays-be/pull/8
