### ISSUE TITLE
Uygulamanın AWS Aurora MySQL DB İle Çalışması

### ISSUE THREAD

**Issue by agitrubard** [afet-yonetim-sistemi/ays-be#84]
Bu issue içerisinde AWS tarafında yeni kurulacak olan Aurora MySQL veritabanı ile uygulamanın çalışabilmesinin sağlanması gerekmekte. Veritabanı oluşturulduktan sonra buradaki issue ilerletilebilir.

---

**DevOps Tarafındaki Issue : https://github.com/afet-yonetim-sistemi/ays-devops/issues/2**

**Comment by furkantrky** [comment]
Aurora MySQL db ayağa kaldırıldı. DB root bilgileri devops tarafındaki issue içerisindeki ilk yorumda bulunmakta.
