### ISSUE TITLE
Atama Süreçlerinin Yönetilmesi İçin Veri Modelinin Oluşturulması

### ISSUE THREAD

**Issue by agitrubard** [afet-yonetim-sistemi/ays-be#88]
Bu issue ile birlikte veri modeli oluşturulmalı, oluşturulan veri modeli uygulamaya yansıtılmalı ve initial verilerin de oluşturulması gerekmektedir.

---

**İsterler**
- Kullanıcı lokasyon bilgilerinin tutulması.
- Atama bilgilerinin tutulması.

> Bu issue tamamlandıktan sonra diğer geliştirmelerin yapılacağı issue'ların içerisine veri modeli ile ilgili bilgilerin güncellenmesi gerekmektedir.

**Comment by Harun170518513** [comment]
@agitrubard @enig @skayikci @microgenius @ilkerCelimli 
 "domainleri oluşturduk service ve controller dışındaki bütün layerları yazdık bir kontrol edebilirseniz seviniriz

https://ibb.co/sbN9YCw
