### ISSUE TITLE
Atama Listeleme Servisinin Hazırlanması

### ISSUE THREAD

**Issue by agitrubard** [afet-yonetim-sistemi/ays-be#93]
Bu issue ile birlikte yöneticiler kendi kurumları için var olan atamaları görüntüleyebilecekleri servisin yazılması gerekmektedir.

---

**Endpoint :**
---
`POST - /api/v1/assignments`

**Header Authorization :**
---
```
Bearer eyJ0eXAiOiJCZWFyZXIiLCJhbGciOiJSUzUxMiJ9.eyJqdGkiOiJiOTdjMzgwNy03Yzc4LTRmNzAtYmFjNS00YWJlMTc2ZDlkOTkiLCJpc3MiOiJBWVMiLCJpYXQiOjE2ODcyNDAyMjUsImV4cCI6MTY4NzI0NzQyNSwiaW5zdGl0dXRpb25JZCI6Ijc3ZWNlMjU2LWJmMGUtNGJiZS04MDFkLTE3MzA4M2Y4YmRjZiIsInVzZXJMYXN0TmFtZSI6IlNpc3RlbWkiLCJ1c2VyVHlwZSI6IkFETUlOIiwidXNlckZpcnN0TmFtZSI6IkFmZXQgWcO2bmV0aW0iLCJ1c2VySWQiOiI5MjYyZjBmYy05M2RiLTRmN2UtODFjNi1hYWFkODVjMmIyMDYiLCJ1c2VybmFtZSI6ImF5cy1hZG1pbi0xIn0.Y8xTAOwhHIqRgqSdnrN7D7OkwnJE7ZbBKfjMygaparuc73WNjKgjJwBhLZ522ULaiWo217_Fw9A0r49imdPTnFGDgPZKnJCof6kTju9m3BIO8c4KcnmauhgXykwHBzsNsUdKq99d9aL72mriNX9QiuCi-T7-tQl2Nnlak338oLEC108oeGgvblXoL6XNaRcnqPnfSmbs0quxf2jJqMYvzWUsw37BnbtiZyZTG91fR9CM-wtmsQLm9-4K74R_nZ2Cq0vU5Rl4gPRGrwOGW6dEzhFSUjVwgIRBi5rSq-u28RnTZWfQ34j6NcJWYd1_0i73aBW5zPhYmBFtTHmnSuL7hw
```

**Request :**
---
```json
{
    "pagination": {
        "page": 1,
        "pageSize": 10
    },
    "filter": {
        "statuses": ["DONE", "AVAILABLE"],
        "phoneNumber": {
            "countryCode": 90,
            "lineNumber": 5333333333
        }
    }
}
```

**Response :**
---
```
{
   "time": "2023-06-20T05:50:25.33188038",
   "httpStatus": "OK",
   "isSuccess": true,
   "response": {
      "content": [
         {
            "id": "49fab2dd-8f3a-4fca-a5f2-d50f06ad5c2e",
            "description": "test",
            "status": "ASSIGNED",
            "firstName": "Ahmet",
            "lastName": "Mehmet",
            "location": {
               "latitude": -81.470448,
               "longitude": 30.333472         
            },
            "user": {
               "id": "49fab2dd-8f3a-4fca-a5f2-d50f06ad5c2e",
               "firstName": "Ahmet",
               "lastName": "Mehmet"
            },
            "createdUser": "AYS",
            "createdAt": "2023-06-20T05:45:42",
            "updatedUser": null,
            "updatedAt": null
         },
         ...
      ],
      "pageNumber": 1,
      "pageSize": 1,
      "totalPageCount": 1,
      "totalElementCount": 1,
      "sortedBy": null,
      "filteredBy": null
   }
}
```

---

**Database :**
---
- **AYS_USER_ASSIGNMENT**
   - `ID` | _VARCHAR(36)_, _NOT NULL_
   - `INSTITUTION_ID` | _VARCHAR(36)_
   - `USER_ID` | _VARCHAR(36)_
   - `DESCRIPTION` | _VARCHAR(2048)_, _NOT NULL_
   - `FIRST_NAME` | _VARCHAR(255)_, _NOT NULL_
   - `LAST_NAME` | _VARCHAR(255)_, _NOT NULL_
   - `COUNTRY_CODE` | _INTEGER(5)_, _NOT NULL_
   - `LINE_NUMBER` | _INTEGER(10)_, _NOT NULL_
   - `POINT` | _POINT_, _NOT NULL_
   - `STATUS` | _VARCHAR(50)_, _NOT NULL_
   - `CREATED_USER` | _VARCHAR(255)_, _NOT NULL_
   - `CREATED_AT` | _TIMESTAMP_, _NOT NULL_
   - `UPDATED_USER` | _VARCHAR(255)_
   - `UPDATED_AT` | _TIMESTAMP_

**Flow :**
---
- Bu servisi sadece yöneticiler görüntüleyebilir.
- Pagination kullanılmalıdır.
- Statü ve Telefon Numarası ile filtreleme yapılabilmeli ve filtreleme alanı opsiyonel olmalı.
- Yöneticiler sadece kendi kurumlarına ait atanmış ya da hiçbir kullanıcıya atanmamış kayıtları görüntüleyebilir. Bu kısıt `institutionId` bilgisi token içerisinden alınarak gerçekleştirilmelidir.
- Atama Statüleri
```
- AVAILABLE
- RESERVED
- ASSIGNED
- IN_PROGRESS
- DONE
```
- Unit (Service), Integration (Controller, Repository), System (End to End) testler yazılmalıdır.
- İlgili endpoint Ortak Postman Collection içerisine eklenmelidir.

**Comment by Harun170518513** [comment]
diagramı çizdik issue yu bitirdik bir kontrol edebilir misiniz
![LISTING USER ASSIGNMENT PROCESS FLOW](https://github.com/afet-yonetim-sistemi/ays-be/assets/123752776/3a3d2f3a-a1cc-4b11-ab6a-9fca82ebfc50)
@agitrubard @enig @Rapter1990

**Comment by Rapter1990** [comment]
@agitrubard @Harun170518513 @moaydogdu @skayikci @emreylmaz 

**Controller** ve **Service** yapısının içeriğini biraz detaylandırmak istedim.

**Controller**

- `getUserAssignments `adında bir method oluşturacağız. Paramater olarak `UserAssignmentListRequest`  ve return türü `AysResponse` olacak
- Service'de tanımladığız `getAllUserAssignments(UserAssignmentListRequest userAssignmentListRequest)` yollayacağız ve oradan `AysPage<UserAssignment>` türde response alacağız
- `pageOfUsersAssignment` elde edebilmek için AysPage<UserAssignment> -> AysPageResponse<UsersAssignment> çevirmeliyiz.
- En sonunda `AysResponse.successOf(pageOfUsersAssignment)` tanımlayarak methodunu bitireceğiz.

**Service**

- `getAllUserAssignments` adında method oluşturup Paramater olarak `UserAssignmentListRequest` ve return türü `AysPage<UserAssignment>`
- `identity`'den `institutionId` alacağız.
- `Specification<UserAssignmentEntity> specification` ile `filter `tanımlayacağız.
- `Page<UserAssignment>` 'ı `userAssignmentRepository.findAll(specification, listRequest.toPageable())` elde edeceğiz.
- `AysPage.of` kullanarak  `AysPage<UserAssignment>` return edeceğiz.

Yapıyı kontrol edebilir misiniz? Ekleyeceğimiz yerler olabilir.
