### ISSUE TITLE
Atama Detay Servisinin Hazırlanması

### ISSUE THREAD

**Issue by agitrubard** [afet-yonetim-sistemi/ays-be#94]
Bu issue ile birlikte yöneticiler kendi kurumları için var olan atamanın detayını görüntüleyebilecekleri servisin yazılması gerekmektedir.

---

**Endpoint :**
---
`GET - /api/v1/assignment/{id}`

**Header Authorization :**
---
```
Bearer eyJ0eXAiOiJCZWFyZXIiLCJhbGciOiJSUzUxMiJ9.eyJqdGkiOiJiOTdjMzgwNy03Yzc4LTRmNzAtYmFjNS00YWJlMTc2ZDlkOTkiLCJpc3MiOiJBWVMiLCJpYXQiOjE2ODcyNDAyMjUsImV4cCI6MTY4NzI0NzQyNSwiaW5zdGl0dXRpb25JZCI6Ijc3ZWNlMjU2LWJmMGUtNGJiZS04MDFkLTE3MzA4M2Y4YmRjZiIsInVzZXJMYXN0TmFtZSI6IlNpc3RlbWkiLCJ1c2VyVHlwZSI6IkFETUlOIiwidXNlckZpcnN0TmFtZSI6IkFmZXQgWcO2bmV0aW0iLCJ1c2VySWQiOiI5MjYyZjBmYy05M2RiLTRmN2UtODFjNi1hYWFkODVjMmIyMDYiLCJ1c2VybmFtZSI6ImF5cy1hZG1pbi0xIn0.Y8xTAOwhHIqRgqSdnrN7D7OkwnJE7ZbBKfjMygaparuc73WNjKgjJwBhLZ522ULaiWo217_Fw9A0r49imdPTnFGDgPZKnJCof6kTju9m3BIO8c4KcnmauhgXykwHBzsNsUdKq99d9aL72mriNX9QiuCi-T7-tQl2Nnlak338oLEC108oeGgvblXoL6XNaRcnqPnfSmbs0quxf2jJqMYvzWUsw37BnbtiZyZTG91fR9CM-wtmsQLm9-4K74R_nZ2Cq0vU5Rl4gPRGrwOGW6dEzhFSUjVwgIRBi5rSq-u28RnTZWfQ34j6NcJWYd1_0i73aBW5zPhYmBFtTHmnSuL7hw
```

**Response :**
---
```
{
   "time": "2023-06-20T05:59:09.376933446",
   "httpStatus": "OK",
   "isSuccess": true,
   "response": {
      "id": "c4b4e4db-5641-41f7-8222-a76deb1c065c",
      "description": "test",
      "status": "DONE",
      "firstName": "Ahmet",
      "lastName": "Mehmet,
      "phoneNumber": {
         "countryCode": "90",
         "lineNumber": "1234567890"
      },
      "location": {
         "latitude": -81.470448,
         "longitude": 30.333472         
      },
      "user": {
         "id": "c4b4e4db-5641-41f7-8222-a76deb1c065c",
         "firstName": "Ahmet",
         "lastName": "Mehmet,
         "phoneNumber": {
            "countryCode": "90",
            "lineNumber": "1234567890"
         },
         "location": {
            "latitude": -81.470448,
            "longitude": 30.333472         
         }
      },
      "createdUser": "AYS",
      "createdAt": "2023-06-20T05:45:42",
      "updatedUser": null,
      "updatedAt": null
    }
}
```

---

**Database :**
---
- **AYS_USER_ASSIGNMENT**
   - `ID` | _VARCHAR(36)_, _NOT NULL_
   - `INSTITUTION_ID` | _VARCHAR(36)_
   - `USER_ID` | _VARCHAR(36)_
   - `DESCRIPTION` | _VARCHAR(2048)_, _NOT NULL_
   - `FIRST_NAME` | _VARCHAR(255)_, _NOT NULL_
   - `LAST_NAME` | _VARCHAR(255)_, _NOT NULL_
   - `COUNTRY_CODE` | _INTEGER(5)_, _NOT NULL_
   - `LINE_NUMBER` | _INTEGER(10)_, _NOT NULL_
   - `POINT` | _POINT_, _NOT NULL_
   - `STATUS` | _VARCHAR(50)_, _NOT NULL_
   - `CREATED_USER` | _VARCHAR(255)_, _NOT NULL_
   - `CREATED_AT` | _TIMESTAMP_, _NOT NULL_
   - `UPDATED_USER` | _VARCHAR(255)_
   - `UPDATED_AT` | _TIMESTAMP_

**Flow :**
---
- Bu servisi sadece yöneticiler görüntüleyebilir.
- Yöneticiler sadece kendi kullanıcılarına atanmış kayıtların ya da atanmamış kayıtların detayını görüntüleyebilir. Yöneticilerin sadece kendi kullanıcılarına ait atanmış kayıtları gösterebilmesi kısmı `institutionId` bilgisi token içerisinden alınarak gerçekleştirilmelidir.
- Atama Statüleri
```
- AVAILABLE
- RESERVED
- ASSIGNED
- IN_PROGRESS
- DONE
```

- Unit (Service), Integration (Controller, Repository), System (End to End) testler yazılmalıdır.
- İlgili endpoint Ortak Postman Collection içerisine eklenmelidir.

**Comment by Harun170518513** [comment]
akış diyagramını yazdık bir kontrol edermisiniz
![Get User Ass,gnment by ,d process flow](https://github.com/afet-yonetim-sistemi/ays-be/assets/123752776/5ae163e2-6ad2-4aec-807a-cc0e2121a152)
@agitrubard @enig @Rapter1990 @emreylmaz

**Comment by Rapter1990** [comment]
@agitrubard @Harun170518513 @moaydogdu @skayikci @emreylmaz 

**Controller** ve **Service** yapısının içeriğini biraz detaylandırmak istedim.

**Controller**

- `@PreAuthorize("hasAnyAuthority('ADMIN')")` `getUserAssignments` için kullanılacak.
- `getAssignmentById` methodu tanımlanacak. Parametre olarak `@UUID String id` alacak. Return türü `AysResponse<UserAssignmentResponse>`
- `assignmentService.getAssignmentById(id)` 'den  `Assignment` sonucu elde edeceğiz.
- `Assignment`'ı `AssignmentResponse`'a dönüştürmek için map kullanacağız.
- `AysResponse.successOf(AssignmentResponse)` return edeceğiz.

**Service**

- getAssignmentById methodu tanımlanacak. Parametre olarak `String id` alacak. Return türü `Assignment`
- `assignmentRepository.findByIdAndInstitutionId` ile `AssignmentEntity` elde edeceğiz.
- `AssignmentEntity`ı `Assignment` a dönüştürmek için map kullanacağız.

Yapıyı kontrol edebilir misiniz? Ekleyeceğimiz yerler olabilir.
