### ISSUE TITLE
Atama Arama Servisinin Hazırlanması

### ISSUE THREAD

**Issue by agitrubard** [afet-yonetim-sistemi/ays-be#95]
Bu issue ile birlikte kullanıcıya en uygun aramanın dönülebilmesi için servis hazırlanması gerekmektedir. 

---

**Endpoint :**
---
`POST - /api/v1/user/assignment/search`

**Header Authorization :**
---
```
Bearer eyJ0eXAiOiJCZWFyZXIiLCJhbGciOiJSUzUxMiJ9.eyJqdGkiOiJlODk5NTQyMS1jYzdhLTQyZGQtYmI4Zi1jZmZkMzk0YWY2ZDQiLCJpc3MiOiJBWVMiLCJpYXQiOjE2ODcyNDEwNTgsImV4cCI6MTY4NzI0ODI1OCwiaW5zdGl0dXRpb25JZCI6Ijc3ZWNlMjU2LWJmMGUtNGJiZS04MDFkLTE3MzA4M2Y4YmRjZiIsInVzZXJMYXN0TmFtZSI6IlNpc3RlbWkiLCJyb2xlcyI6WyJWT0xVTlRFRVIiXSwidXNlclR5cGUiOiJVU0VSIiwidXNlckZpcnN0TmFtZSI6IkFmZXQgWcO2bmV0aW0iLCJ1c2VySWQiOiJjNGI0ZTRkYi01NjQxLTQxZjctODIyMi1hNzZkZWIxYzA2NWMiLCJ1c2VybmFtZSI6IjIzMjE4MCJ9.S-M7SUY4s7cwHyApApkfpRH6W8M_hRHqfnwdo3_ls-qm7F0yWHdSOqF2ZvbvPGolZPhUZgyyUc5U4gMT3ThDP_yAT1dKe5MV6TzYc2Ro1lF1fmcx7DwlQOv2nddyclaCQbcJ7nu3IyyqDM71PmuX1lx2jYkyNqGLHcM5aJzmpJnmXKZoKxkhUY4xOq-jiDrsGiYnvfxiR_76Q9193uNzslTntDNM7YVn_YsULSjZXjAryupCcsq5y2kZ7nQ7jpvvOWP_hXUSB5siHDbKYwMNklC9RWl_7UFLMy-zbgTcuH6tHg712wRO25aahedzcuUy2iIXetuZrMTSeZ7tji8VEg
```

**Request :**
```
{
    "latitude": -81.470448,
    "longtitude": 30.333472
}
```

**Response :**
---
```
{
    "time": "2023-06-20T05:59:09.376933446",
    "httpStatus": "OK",
    "isSuccess": true,
    "response": {
        "id": "c4b4e4db-5641-41f7-8222-a76deb1c065c",
        "description": "test",
        "latitude": -81.470448,
        "longitude": 30.333472,
        "status": "RESERVED"
    }
}
```

---

**Database :**
---
- **AYS_USER_ASSIGNMENT**
   - `ID` | _VARCHAR(36)_, _NOT NULL_
   - `INSTITUTION_ID` | _VARCHAR(36)_
   - `USER_ID` | _VARCHAR(36)_
   - `DESCRIPTION` | _VARCHAR(2048)_, _NOT NULL_
   - `FIRST_NAME` | _VARCHAR(255)_, _NOT NULL_
   - `LAST_NAME` | _VARCHAR(255)_, _NOT NULL_
   - `COUNTRY_CODE` | _INTEGER(5)_, _NOT NULL_
   - `LINE_NUMBER` | _INTEGER(10)_, _NOT NULL_
   - `POINT` | _POINT_, _NOT NULL_
   - `STATUS` | _VARCHAR(50)_, _NOT NULL_
   - `CREATED_USER` | _VARCHAR(255)_, _NOT NULL_
   - `CREATED_AT` | _TIMESTAMP_, _NOT NULL_
   - `UPDATED_USER` | _VARCHAR(255)_
   - `UPDATED_AT` | _TIMESTAMP_

**Flow :**
---
- Bu servisi sadece kullanıcılar görüntüleyebilir.
- Kullanıcı status değeri `ACTIVE` ve supportStatus değeri `READY` ise bu servisten cevap alabilecek, aksi hâlde uygun hata mesajının dönmesi beklenmekte. Bu kısıt `userId` bilgisi token içerisinden alınarak gerçekleştirilmelidir.
- Bu servise `latitude` ve `longtitude` bilgileri işlenerek en uygun atama bilgisi işlenerek dönülecek.
- En uygun atama bulunurken `AVAILABLE` olan en uygun atama bulunmalı ve bu atama bulunduktan sonra `RESERVED` statüsü, `USER_ID` ve `INSTITUTION_ID` alanları ilgili kullanıcı için veritabanına yazılarak opsiyonlanmalıdır.
- Atama Statüleri
```
- AVAILABLE
- RESERVED
- ASSIGNED
- IN_PROGRESS
- DONE
```
- Unit (Service), Integration (Controller, Repository), System (End to End) testler yazılmalıdır.
- İlgili endpoint Ortak Postman Collection içerisine eklenmelidir.

**Comment by Rapter1990** [comment]
We can use this query shown below for this process

```
SELECT * FROM assignments
WHERE ACOS(SIN(RADIANS(:lat)) * SIN(RADIANS(latitude))
     + COS(RADIANS(:lat)) * COS(RADIANS(latitude))
     * COS(RADIANS(:lon) - RADIANS(longitude))) * 6371 <= :radius
```

Here is the **explanation** shown below

The formula inside the ACOS function calculates the distance between two points on the Earth's surface using the Haversine formula. It takes the latitude and longitude of both points into account.

The 6371 is used to convert the result of the Haversine formula from radians to kilometers. Multiplying the result by the Earth's radius in kilometers gives the distance between the two points in kilometers.

Can you check it ? @agitrubard @skayikci @emreylmaz @Harun170518513 @moaydogdu

**Comment by agitrubard** [comment]
Arama veritabanından mı yapılacak, yoksa AYA tarafındaki servisler mi kullanılacak buradaki konu netleştirildikten sonra ilerlenmesi daha doğru olabilir.

Eğer veritabanından yapılacaksa aşağıdaki dokümanlardan yararlanılabilir;
- https://dev.mysql.com/doc/refman/8.0/en/spatial-types.html
- https://www.baeldung.com/java-geospatial-applications
- https://dev.mysql.com/doc/refman/8.0/en/create-spatial-reference-system.html

**Comment by Harun170518513** [comment]
akışı çizdik 
![User Assignment Search Flow Diagram](https://github.com/afet-yonetim-sistemi/ays-be/assets/123752776/7beb96af-c106-4b1f-b7dd-84a82aaaa270)
Kontrol edebilir misiniz @agitrubard @enig @Rapter1990

**Comment by Rapter1990** [comment]
@agitrubard @Harun170518513 @moaydogdu @skayikci @emreylmaz 

**Controller** ve **Service** yapısının içeriğini biraz detaylandırmak istedim.

**Controller**

- `@PreAuthorize("hasAnyAuthority('USER')")` `searchAssignments` için kullanılacak.
- `searchAssignments `adında bir method oluşturacağız. Paramater olarak `UserLocationRequestRequest`  ve return türü `AysResponse` olacak
- Service'de tanımladığız `searchAssignments(UserLocationRequestRequest userLocationRequestRequest)` yollayacağız ve oradan `AysPage<UserAssignment>` türde response alacağız
- `pageOfUsersAssignment` elde edebilmek için `AysPage<UserAssignment>` -> `AysPageResponse<UsersAssignmentResponse>` çevirmeliyiz.
- En sonunda `AysResponse.successOf(pageOfUsersAssignment)` tanımlayarak methodunu bitireceğiz.

**Service**

- `searchAssignments` adında method oluşturup Paramater olarak `UserLocationRequestRequest` ve return türü `AysPage<UserAssignment>`
- `identity`'den `userId` alacağız.
- `userStatus == UserStatus.ACTIVE` && `supportStatus == SupportStatus.READY` değilse throw exception yapacağız.
- `Repository`'deki `findAssignmentByLocation`'dan `UserLocationRequestRequest` 'den `latitude` ve `longitude` parametre alarak işlem yapacak `AssignmentEntity` `return` edecek.
- `assignmentEntity` 'de `status`unu `AssignmentStatus.RESERVED` olarak assign edeceğiz.
- `assignmentEntity` 'de `userId` 'yi assign edeceğiz.
- `assignmentRepository.save(assignmentEntity)` diyerek assignment update edeceğiz.
- `assignmentEntityToAssignmentMapper.map(assignmentEntity)` ile `UserAssignment` elde edeceğiz.
- `AysPage.of` kullanarak `AysPage<UserAssignment>` return edeceğiz.

Yapıyı kontrol edebilir misiniz? Ekleyeceğimiz yerler olabilir.

**Comment by agitrubard** [comment]
Burası yardımcı olabilir
```
# Search Nearest Location
SELECT ID,
       ST_DISTANCE(ST_GeomFromText('POINT(40.991739 29.024168)', 4326), POINT) AS DISTANCE,
       DESCRIPTION,
       FIRST_NAME,
       LAST_NAME,
       COUNTRY_CODE,
       LINE_NUMBER,
       STATUS,
       POINT,
       CREATED_USER,
       CREATED_AT
FROM AYS_USER_ASSIGNMENT
ORDER BY DISTANCE
LIMIT 1;


# Distance To KM

# 1.18 KM
SELECT CAST((ST_DISTANCE(ST_GeomFromText('POINT(40.991739 29.024168)', 4326),
                        ST_GeomFromText('POINT(40.981210 29.026083)', 4326))) / 1000 AS DECIMAL(10, 2)) AS DISTANCE;

# 0.0004 KM
SELECT CAST((ST_DISTANCE(ST_GeomFromText('POINT(40.991739 29.024168)', 4326),
                        ST_GeomFromText('POINT(40.991739 29.024163)', 4326))) / 1000 AS DECIMAL(10, 4)) AS DISTANCE;
```
