### ISSUE TITLE
Atama Onaylama Servisinin Hazırlanması

### ISSUE THREAD

**Issue by agitrubard** [afet-yonetim-sistemi/ays-be#96]
### #103 tamamlanmadan buradaki issue'ya başlanmamalı!

Bu issue ile birlikte kullanıcıya ait opsiyonlanmış atamanın onaylanması için servis yazılması gerekmektedir.

---

**Endpoint :**
---
`PATCH - /api/v1/user/assignment/approve`

**Header Authorization :**
---
```
Bearer eyJ0eXAiOiJCZWFyZXIiLCJhbGciOiJSUzUxMiJ9.eyJqdGkiOiJlODk5NTQyMS1jYzdhLTQyZGQtYmI4Zi1jZmZkMzk0YWY2ZDQiLCJpc3MiOiJBWVMiLCJpYXQiOjE2ODcyNDEwNTgsImV4cCI6MTY4NzI0ODI1OCwiaW5zdGl0dXRpb25JZCI6Ijc3ZWNlMjU2LWJmMGUtNGJiZS04MDFkLTE3MzA4M2Y4YmRjZiIsInVzZXJMYXN0TmFtZSI6IlNpc3RlbWkiLCJyb2xlcyI6WyJWT0xVTlRFRVIiXSwidXNlclR5cGUiOiJVU0VSIiwidXNlckZpcnN0TmFtZSI6IkFmZXQgWcO2bmV0aW0iLCJ1c2VySWQiOiJjNGI0ZTRkYi01NjQxLTQxZjctODIyMi1hNzZkZWIxYzA2NWMiLCJ1c2VybmFtZSI6IjIzMjE4MCJ9.S-M7SUY4s7cwHyApApkfpRH6W8M_hRHqfnwdo3_ls-qm7F0yWHdSOqF2ZvbvPGolZPhUZgyyUc5U4gMT3ThDP_yAT1dKe5MV6TzYc2Ro1lF1fmcx7DwlQOv2nddyclaCQbcJ7nu3IyyqDM71PmuX1lx2jYkyNqGLHcM5aJzmpJnmXKZoKxkhUY4xOq-jiDrsGiYnvfxiR_76Q9193uNzslTntDNM7YVn_YsULSjZXjAryupCcsq5y2kZ7nQ7jpvvOWP_hXUSB5siHDbKYwMNklC9RWl_7UFLMy-zbgTcuH6tHg712wRO25aahedzcuUy2iIXetuZrMTSeZ7tji8VEg
```

**Response :**
---
```
{
    "time": "2023-06-20T05:59:09.376933446",
    "httpStatus": "OK",
    "isSuccess": true
}
```

---

**Database :**
---
- **AYS_USER_ASSIGNMENT**
   - `ID` | _VARCHAR(36)_, _NOT NULL_
   - `INSTITUTION_ID` | _VARCHAR(36)_
   - `USER_ID` | _VARCHAR(36)_
   - `DESCRIPTION` | _VARCHAR(2048)_, _NOT NULL_
   - `FIRST_NAME` | _VARCHAR(255)_, _NOT NULL_
   - `LAST_NAME` | _VARCHAR(255)_, _NOT NULL_
   - `COUNTRY_CODE` | _INTEGER(5)_, _NOT NULL_
   - `LINE_NUMBER` | _INTEGER(10)_, _NOT NULL_
   - `POINT` | _POINT_, _NOT NULL_
   - `STATUS` | _VARCHAR(50)_, _NOT NULL_
   - `CREATED_USER` | _VARCHAR(255)_, _NOT NULL_
   - `CREATED_AT` | _TIMESTAMP_, _NOT NULL_
   - `UPDATED_USER` | _VARCHAR(255)_
   - `UPDATED_AT` | _TIMESTAMP_

**Flow :**
---
- Bu servisi sadece kullanıcılar görüntüleyebilir.
- İlgili Kullanıcı sadece atamayı opsiyonlamışsa bu servisi kullanabilecek.
- Bu servis içerisindeki atama ilgili kullanıcının ID bilgisi ile işlemlerin yapılması gerekmektedir. Bu kısıt `userId` bilgisi token içerisinden alınarak gerçekleştirilmelidir.
- İlgili atama bulunduktan sonra `RESERVED` statüsünde ise aksiyon alınabilmeli.
- Atama, ilgili kullanıcıya atanması için atama statüsü `ASSIGNED` ve ilgili kullanıcı statüsü ise `BUSY` olarak güncellenmelidir.
- Atama Statüleri
```
- AVAILABLE
- RESERVED
- ASSIGNED
- IN_PROGRESS
- DONE
```
- Unit (Service), Integration (Controller, Repository), System (End to End) testler yazılmalıdır.
- İlgili endpoint Ortak Postman Collection içerisine eklenmelidir.

**Comment by Harun170518513** [comment]
Geçerli Servis bitirdik akış diagramı şekildedir 
![Approve User Assignment Diagram](https://github.com/afet-yonetim-sistemi/ays-be/assets/123752776/134e811e-9193-40ad-b508-9bb9f4aef7ad)
@agitrubard @Rapter1990 @enig @emreylmaz

**Comment by Rapter1990** [comment]
@agitrubard @Harun170518513 @moaydogdu @skayikci @emreylmaz 

**Controller** ve **Service** yapısının içeriğini biraz detaylandırmak istedim.

**Controller**

- `@PreAuthorize("hasAnyAuthority('ADMIN')")` `getUserAssignments` için kullanılacak.
- `approveAssignment` methodu tanımlanacak. Return türü `AysResponse<Void>`
- `assignmentService.approveAssignment` 'den  return `void `olacak
- `AysResponse.SUCCESS` return edeceğiz.

**Service**

- approveAssignment methodu tanımlanacak. Return türü `void`
- `identity`'den `userId` alacağız.
- `AssignmentEntity assignment = findAssignmentByUserId(userId)` 'den AssignmentEntity elde edeceğiz.
- Aşağıdaki işlemleri uygulayıp -> Assisgnment Statusu Assignment ve UserStatus Busy yapıp. Assignment'i update edeceğiz.
```
assignment.updateAssignmentStatus(AssignmentStatus.ASSIGNED);
assignment.getUser().setStatus(UserStatus.BUSY);
assignmentRepository.save(assignment);
```

Yapıyı kontrol edebilir misiniz? Ekleyeceğimiz yerler olabilir.
